In [1]:
#function to test models 
import nest_asyncio
import warnings
from mb_utils.src.logging import logger

nest_asyncio.apply()
warnings.filterwarnings("ignore")

In [2]:
from mb_pytorch.utils.version import version
version

'1.0.72'

In [3]:
from mb_pytorch.dataloader.loader import DataLoader

k = DataLoader('../scripts/detection/object_detection.yaml',logger=logger)
k_data = k.data_dict['data']
model_data_dict = k.data_dict['model']

Sat 00:58:14,291 INF Read data from yaml file: [{'data': {'file': {'root': '/home/malav/Desktop/mb_packages/mb_pytorch/data/fruit_dat


In [4]:
from mb_pytorch.training.train_params import train_helper
model_yaml_data = k.data_dict['model']
loss_attr,optimizer_attr,optimizer_dict,scheduler_attr,scheduler_dict = train_helper(model_yaml_data) 

In [5]:
from torch.utils.tensorboard import SummaryWriter
import os

path_logs = os.path.join(os.path.split(k_data['file']['root'])[0], 'logs')
writer = SummaryWriter(log_dir=path_logs)


In [6]:
train_loader,val_loader,train_dataset,test_dataset = k.data_load()


300row [00:00, 110048.21row/s]
Sat 00:58:15,916 INF Loaded dataframe from /home/malav/Desktop/mb_packages/mb_pytorch/data/fruit_dataset/fruit_dataset_final.csv usin
Sat 00:58:15,919 INF Data file: {'root': '/home/malav/Desktop/mb_packages/mb_pytorch/data/fruit_dataset/fruit_dataset_final.csv', 've
Sat 00:58:15,921 INF Data columns: Index(['image_id', 'image_path', 'bbox', 'label', 'image_type'], dtype='object')                  
Sat 00:58:15,923 INF Data will be split into train and validation according to train_file input : True                               
Sat 00:58:15,925 INF If unnamed columns are present, they will be removed.                                                           
Sat 00:58:15,927 INF If duplicate rows are present, they will be removed.                                                            
Sat 00:58:15,934 INF Length of data after removing invalid paths: 300                                                                
Sat 00:58:15,935 INF Skipping i

In [7]:
train_dataset.__getitem__(0)

(tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],
 
         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],
 
         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]),
 {'bbox': tensor([[ 26,  69, 604, 581]], dtype=torch.int32),
  'label': ['orange']})

In [8]:
test_dataset.__getitem__(4)

(tensor([[[0.2431, 0.2431, 0.2549,  ..., 0.2941, 0.2745, 0.2667],
          [0.2275, 0.2353, 0.2431,  ..., 0.2941, 0.2784, 0.2706],
          [0.2000, 0.2118, 0.2196,  ..., 0.2980, 0.2784, 0.2706],
          ...,
          [0.3098, 0.0000, 0.0314,  ..., 0.2275, 0.2196, 0.1961],
          [0.3137, 0.0588, 0.0000,  ..., 0.2039, 0.2157, 0.2039],
          [0.5020, 0.2510, 0.0000,  ..., 0.1608, 0.1843, 0.1686]],
 
         [[0.4549, 0.4627, 0.4745,  ..., 0.4392, 0.4157, 0.4078],
          [0.4353, 0.4471, 0.4588,  ..., 0.4392, 0.4196, 0.4118],
          [0.4039, 0.4196, 0.4314,  ..., 0.4431, 0.4314, 0.4235],
          ...,
          [0.5137, 0.1176, 0.2235,  ..., 0.3529, 0.3451, 0.3216],
          [0.5333, 0.2706, 0.1608,  ..., 0.3373, 0.3490, 0.3373],
          [0.7294, 0.4627, 0.1176,  ..., 0.3098, 0.3333, 0.3176]],
 
         [[0.3176, 0.3255, 0.3373,  ..., 0.3373, 0.3216, 0.3137],
          [0.3059, 0.3098, 0.3294,  ..., 0.3373, 0.3255, 0.3176],
          [0.2863, 0.2902, 0.3137,  ...,

In [9]:
for id, (image, target) in enumerate(train_loader):
    print(image.shape)
    print(target)
    print(id)
    break

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 173, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 173, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 212, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to resize storage that is not resizable


In [25]:
for batch_idx, (images, targets) in enumerate(train_loader):
    print("image is : {}".format(images.shape))
    images_l = list(image.to('cpu') for image in images) 
    print("target is : {}".format(targets))
    d = {}
    d['boxes'] = targets[1][:]
    d['labels'] = targets[0][:]
    targets = [{k: v.to('cpu') for k, v in t.items()} for t in [d]]
    #print("image_new is : {}".format(images_l))
    print("target_new is : {}".format(targets))
    break

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 173, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 173, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 212, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to resize storage that is not resizable


In [10]:
targets[0]['labels']

NameError: name 'targets' is not defined

In [11]:
from mb_pytorch.models.modelloader import ModelLoader
model_data_load = ModelLoader(k.data_dict['model'])
model =  model_data_load.get_model()

Sat 00:42:44,904 INF Model fasterrcnn_resnet50_fpn loaded from torchvision.models.                                                   


In [12]:
targets[0]

NameError: name 'targets' is not defined

In [13]:
targets[0]

NameError: name 'targets' is not defined

In [14]:
for target in targets:
    print(target['boxes'])
    break

NameError: name 'targets' is not defined

In [15]:
model(images_l,targets)

NameError: name 'images_l' is not defined

In [ ]:
images.shape

torch.Size([4, 3, 218, 178])

In [ ]:
#tuple(targets)
lk = [{k: v for k, v in t.items()} for t in tuple(targets)]
lk

[{'boxes': tensor([[ 95,  71, 226, 313],
          [ 72,  94, 221, 306],
          [216,  59,  91, 126],
          [622, 257, 564, 781]]),
  'labels': tensor([2880, 2937, 8692, 5805])}]

In [ ]:
target[i] if target[0] is not None else None

KeyError: 0

In [ ]:
len(images_l)

4

In [ ]:
boxes_list = [target['boxes'] for target in targets]
boxes_list

[tensor([[ 95,  71, 226, 313],
         [ 72,  94, 221, 306],
         [216,  59,  91, 126],
         [622, 257, 564, 781]])]

In [ ]:
boxes_label = [target['labels'] for target in targets]
boxes_label

[tensor([2880, 2937, 8692, 5805])]

In [ ]:
boxes_list[0][0]

tensor([ 95,  71, 226, 313])

In [ ]:
boxes_label[0][0]

tensor(2880)

In [ ]:
for i in range(len(boxes_list[0][0].tolist())):
    print(boxes_list[0][1].tolist()[i])


72
94
221
306


In [ ]:
boxes_list[0][1].tolist()

[72, 94, 221, 306]

In [ ]:
import torch
lk_new = []
for i in range(len(images_l)):
    temp_dict = {}
    # temp_l = []
    # temp_l_final = []
    # for i in range(len(boxes_list[0][0])):
    #     temp_l.append(int(boxes_list[0][i].tolist()[i]))
    #     temp_l_final.append(temp_l)
    temp_dict['boxes'] = torch.tensor([boxes_list[0][i].tolist()])
    temp_dict['labels'] = torch.tensor([boxes_label[0][i]])
    lk_new.append(temp_dict)
lk_new

[{'boxes': tensor([[ 95,  71, 226, 313]]), 'labels': tensor([2880])},
 {'boxes': tensor([[ 72,  94, 221, 306]]), 'labels': tensor([2937])},
 {'boxes': tensor([[216,  59,  91, 126]]), 'labels': tensor([8692])},
 {'boxes': tensor([[622, 257, 564, 781]]), 'labels': tensor([5805])}]

In [64]:
model(images_l,lk_new)

AssertionError: All bounding boxes should have positive height and width. Found invalid box [970.7864990234375, 264.9587097167969, 408.9887390136719, 565.8440551757812] for target at index 2.

In [16]:
from mb_pytorch.detection.training import detection_train_loop


In [17]:
detection_train_loop(k,model_data_dict,writer=writer,logger=logger)

Sat 00:43:06,477 INF Training loop Starting                                                                                          
Sat 00:43:06,906 INF Model fasterrcnn_resnet50_fpn loaded from torchvision.models.                                                   
Sat 00:43:06,908 INF Model Loaded                                                                                                    
300row [00:00, 147479.04row/s]
Sat 00:43:06,914 INF Loaded dataframe from /home/malav/Desktop/mb_packages/mb_pytorch/data/fruit_dataset/fruit_dataset_final.csv usin
Sat 00:43:06,916 INF Data file: {'root': '/home/malav/Desktop/mb_packages/mb_pytorch/data/fruit_dataset/fruit_dataset_final.csv', 've
Sat 00:43:06,918 INF Data columns: Index(['image_id', 'image_path', 'bbox', 'label', 'image_type'], dtype='object')                  
Sat 00:43:06,920 INF Data will be split into train and validation according to train_file input : True                               
Sat 00:43:06,922 INF If unnamed

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 173, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 173, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malav/Desktop/mb_packages/mb_pytorch/env/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 212, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to resize storage that is not resizable
