In [1]:
#function to test models 
import nest_asyncio
import warnings
from mb_utils.src.logging import logger

nest_asyncio.apply()
warnings.filterwarnings("ignore")


In [12]:
from mb_pytorch.models.modelloader import ModelLoader,ModelExtractor
from mb_pytorch.dataloader.loader import DataLoader

k = DataLoader('../scripts/model_load/loader_y.yaml',logger=logger)
k_data = k.data_dict['data']
model_data_dict = k.data_dict['model']

ImportError: cannot import name 'ModelExtractor' from 'mb_pytorch.models.modelloader' (/home/malav/.local/lib/python3.8/site-packages/mb_pytorch/models/modelloader.py)

In [3]:
k.data_dict

{'data': {'from_datasets': 'Flowers102',
  'from_file': False,
  'work_dir': '/home/malav/mb_pytorch/data/',
  'file': '/home/malav/mb_pytorch/data/csv/file_data.csv',
  'use_img_dir': True,
  'img_dir': '/home/malav/mb_pytorch/data/images1/',
  'thresholding_pd': 0},
 'train_params': {'batch_size': 32,
  'num_workers': 4,
  'pin_memory': True,
  'shuffle': True,
  'seed': 42},
 'test_params': {'batch_size': 32,
  'num_workers': 4,
  'pin_memory': True,
  'shuffle': False,
  'seed': 42},
 'transforms_list': {'transform': True,
  'resize': {'val': True, 'args': {'size': [64, 64]}},
  'random_crop': {'val': False, 'args': {'size': [62, 62]}},
  'random_horizontal_flip': {'val': True, 'args': {'p': 0.5}},
  'random_vertical_flip': {'val': False, 'args': {'p': 0.5}},
  'random_rotation': {'val': False, 'args': {'degrees': 90}},
  'random_grayscale': {'val': False, 'args': {'p': 0.1}},
  'random_color_jitter': {'val': True,
   'args': {'brightness': 0.4,
    'contrast': 0.4,
    'saturation

In [4]:
model_data_load = ModelLoader(k.data_dict['model'])

model_data =  model_data_load.get_model()
model_data_ex = ModelExtractor(model_data)

train_loader,val_loader,_,_ = k.data_load()

all_data = k.data_dict

Thu 23:33:53,369 INF Model resnet50 loaded from torchvision.models.                                                                  
Thu 23:33:53,371 INF Data file: Flowers102 loading from torchvision.datasets.                                                        
Thu 23:33:53,385 INF Read data from yaml file: [{'data': {'from_datasets': 'Flowers102', 'from_file': False, 'work_dir': '/home/malav
Thu 23:33:53,387 INF transforms: [ToTensor(), Resize(size=[64, 64], interpolation=bilinear, max_size=None, antialias=warn), RandomHor
Thu 23:33:53,538 INF Read data from yaml file: [{'data': {'from_datasets': 'Flowers102', 'from_file': False, 'work_dir': '/home/malav
Thu 23:33:53,540 INF transforms: [ToTensor(), Resize(size=[64, 64], interpolation=bilinear, max_size=None, antialias=warn), RandomHor


In [5]:
from mb_pytorch.training.train_params import train_helper

model_yaml_data = k.data_dict['model']
loss_attr,optimizer_attr,optimizer_dict,scheduler_attr,scheduler_dict = train_helper(model_yaml_data) 

In [6]:
import torch.nn.functional as F
loss_attr = F.cross_entropy

In [7]:
print(loss_attr)
print(optimizer_attr)
print(optimizer_dict)
print(scheduler_attr)
print(scheduler_dict)

<function cross_entropy at 0x7f67e0001d30>
<class 'torch.optim.adam.Adam'>
{'lr': 0.01, 'betas': [0.9, 0.999], 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}
<class 'torch.optim.lr_scheduler.StepLR'>
{'step_size': 3, 'gamma': 0.2}


In [8]:

from torch.utils.tensorboard import SummaryWriter
import os
import torch
## setting the trianing params

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

optimizer = optimizer_attr(model_data.parameters(),**optimizer_dict)
scheduler = scheduler_attr(optimizer,**scheduler_dict)

best_val_loss = float('inf')

path_logs = os.path.join(all_data['data']['work_dir'], 'logs')
writer = SummaryWriter(log_dir=path_logs)

all_model_data= k.data_dict['model']


In [9]:
from mb_utils.src.logging import logger
from itertools import islice


train_loader10 = islice(train_loader, 10)
val_loader10 = islice(val_loader, 10)


In [10]:
from mb_pytorch.classification.training import classification_train_loop

classification_train_loop(k_data,model_data_dict,model_data,train_loader,val_loader,loss_attr,optimizer,scheduler=None,writer=writer,logger=logger,gradcam=None,device=device)
####gradcam_layers=['model_data.features[-1][0]','model_data.features[0][0]']

  0%|          | 0/30 [00:00<?, ?it/s]

model train true


Thu 23:33:59,920 INF Training Started                                                                                                
Thu 23:34:02,223 INF Epoch 1 - Batch 1 - Train Loss: 4.862838268280029                                                               
Thu 23:34:03,225 INF Epoch 1 - Batch 2 - Train Loss: 30.037208557128906                                                              
Thu 23:34:04,579 INF Epoch 1 - Batch 3 - Train Loss: 18.827743530273438                                                              
Thu 23:34:05,566 INF Epoch 1 - Batch 4 - Train Loss: 16.9736328125                                                                   
Thu 23:34:06,558 INF Epoch 1 - Batch 5 - Train Loss: 22.408655166625977                                                              
Thu 23:34:07,542 INF Epoch 1 - Batch 6 - Train Loss: 18.736263275146484                                                              
Thu 23:34:08,523 INF Epoch 1 - Batch 7 - Train Loss: 9.2372732

lr =  0.01
model train false


Thu 23:34:41,452 INF Epoch 1 - Batch 32 - Val Loss: 6091.531                                                                         
Thu 23:34:41,929 INF Epoch 1 - Batch 32 - Val Loss: 14311.769                                                                        
Thu 23:34:42,396 INF Epoch 1 - Batch 32 - Val Loss: 19986.542                                                                        
Thu 23:34:42,697 INF Epoch 1 - Batch 32 - Val Loss: 28331.622                                                                        
Thu 23:34:43,009 INF Epoch 1 - Batch 32 - Val Loss: 33054.179                                                                        
Thu 23:34:43,307 INF Epoch 1 - Batch 32 - Val Loss: 40019.529                                                                        
Thu 23:34:43,612 INF Epoch 1 - Batch 32 - Val Loss: 45349.700                                                                        
Thu 23:34:43,936 INF Epoch 1 - Batch 32 - Val Loss: 50343.690 

tensor([54, 25, 18, 54, 54,  5,  5, 54,  5, 57,  5,  5, 54, 54, 54, 54, 54,  5,
         5, 80, 54, 54, 54, 57, 54, 54, 54, 54])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:34:52,982 INF Epoch 1 - Best Model Saved                                                                                      
  3%|▎         | 1/30 [00:53<25:38, 53.07s/it]

model train true


Thu 23:34:52,988 INF Training Started                                                                                                
Thu 23:34:55,390 INF Epoch 2 - Batch 1 - Train Loss: 4.687519550323486                                                               
Thu 23:34:56,466 INF Epoch 2 - Batch 2 - Train Loss: 4.899583339691162                                                               
Thu 23:34:58,063 INF Epoch 2 - Batch 3 - Train Loss: 5.411063194274902                                                               
Thu 23:34:59,133 INF Epoch 2 - Batch 4 - Train Loss: 5.6577653884887695                                                              
Thu 23:35:00,249 INF Epoch 2 - Batch 5 - Train Loss: 4.517134666442871                                                               
Thu 23:35:01,380 INF Epoch 2 - Batch 6 - Train Loss: 5.881016254425049                                                               
Thu 23:35:02,475 INF Epoch 2 - Batch 7 - Train Loss: 5.3813591

lr =  0.01
model train false


Thu 23:35:31,448 INF Epoch 2 - Batch 32 - Val Loss: 4.604                                                                            
Thu 23:35:31,863 INF Epoch 2 - Batch 32 - Val Loss: 9.310                                                                            
Thu 23:35:32,278 INF Epoch 2 - Batch 32 - Val Loss: 13.866                                                                           
Thu 23:35:32,555 INF Epoch 2 - Batch 32 - Val Loss: 18.485                                                                           
Thu 23:35:32,822 INF Epoch 2 - Batch 32 - Val Loss: 24.965                                                                           
Thu 23:35:33,101 INF Epoch 2 - Batch 32 - Val Loss: 29.864                                                                           
Thu 23:35:33,418 INF Epoch 2 - Batch 32 - Val Loss: 34.521                                                                           
Thu 23:35:33,701 INF Epoch 2 - Batch 32 - Val Loss: 39.443    

tensor([ 3,  3, 53,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        89,  3,  3,  3,  3,  3,  3,  3,  3,  3])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:35:41,403 INF Epoch 2 - Best Model Saved                                                                                      
  7%|▋         | 2/30 [01:41<23:29, 50.34s/it]

model train true


Thu 23:35:41,419 INF Training Started                                                                                                
Thu 23:35:43,535 INF Epoch 3 - Batch 1 - Train Loss: 4.621374607086182                                                               
Thu 23:35:44,535 INF Epoch 3 - Batch 2 - Train Loss: 4.566854953765869                                                               
Thu 23:35:46,029 INF Epoch 3 - Batch 3 - Train Loss: 4.595395088195801                                                               
Thu 23:35:47,097 INF Epoch 3 - Batch 4 - Train Loss: 4.690101623535156                                                               
Thu 23:35:48,365 INF Epoch 3 - Batch 5 - Train Loss: 4.638308525085449                                                               
Thu 23:35:49,369 INF Epoch 3 - Batch 6 - Train Loss: 4.598577976226807                                                               
Thu 23:35:50,374 INF Epoch 3 - Batch 7 - Train Loss: 4.5960922

lr =  0.01
model train false


Thu 23:36:21,350 INF Epoch 3 - Batch 32 - Val Loss: 4.606                                                                            
Thu 23:36:21,717 INF Epoch 3 - Batch 32 - Val Loss: 10.618                                                                           
Thu 23:36:22,064 INF Epoch 3 - Batch 32 - Val Loss: 15.205                                                                           
Thu 23:36:22,449 INF Epoch 3 - Batch 32 - Val Loss: 19.768                                                                           
Thu 23:36:22,733 INF Epoch 3 - Batch 32 - Val Loss: 25.282                                                                           
Thu 23:36:23,022 INF Epoch 3 - Batch 32 - Val Loss: 30.021                                                                           
Thu 23:36:23,331 INF Epoch 3 - Batch 32 - Val Loss: 34.616                                                                           
Thu 23:36:23,632 INF Epoch 3 - Batch 32 - Val Loss: 39.216    

tensor([21, 21, 21, 21, 21, 21, 70, 21, 21, 21, 21, 27, 21, 21, 21, 21, 21, 21,
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:36:32,567 INF Epoch 3 - Best Model Saved                                                                                      
 10%|█         | 3/30 [02:32<22:49, 50.71s/it]

model train true


Thu 23:36:32,581 INF Training Started                                                                                                
Thu 23:36:34,463 INF Epoch 4 - Batch 1 - Train Loss: 4.569247245788574                                                               
Thu 23:36:35,219 INF Epoch 4 - Batch 2 - Train Loss: 4.607174873352051                                                               
Thu 23:36:36,482 INF Epoch 4 - Batch 3 - Train Loss: 4.585273742675781                                                               
Thu 23:36:37,246 INF Epoch 4 - Batch 4 - Train Loss: 4.763659954071045                                                               
Thu 23:36:37,992 INF Epoch 4 - Batch 5 - Train Loss: 4.668386459350586                                                               
Thu 23:36:38,732 INF Epoch 4 - Batch 6 - Train Loss: 4.486197471618652                                                               
Thu 23:36:39,508 INF Epoch 4 - Batch 7 - Train Loss: 4.5680050

lr =  0.01
model train false


Thu 23:37:06,279 INF Epoch 4 - Batch 32 - Val Loss: 4.619                                                                            
Thu 23:37:06,651 INF Epoch 4 - Batch 32 - Val Loss: 9.157                                                                            
Thu 23:37:06,920 INF Epoch 4 - Batch 32 - Val Loss: 13.755                                                                           
Thu 23:37:07,205 INF Epoch 4 - Batch 32 - Val Loss: 18.097                                                                           
Thu 23:37:07,464 INF Epoch 4 - Batch 32 - Val Loss: 22.751                                                                           
Thu 23:37:07,737 INF Epoch 4 - Batch 32 - Val Loss: 27.338                                                                           
Thu 23:37:07,985 INF Epoch 4 - Batch 32 - Val Loss: 31.953                                                                           
Thu 23:37:08,246 INF Epoch 4 - Batch 32 - Val Loss: 36.567    

tensor([85, 85, 85, 85, 85, 27, 26, 85, 85, 27, 85, 85, 53, 85, 85, 26, 53, 85,
        85, 85, 85, 26, 85, 85, 53, 85, 26, 46])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:37:15,894 INF Epoch 4 - Best Model Saved                                                                                      
 13%|█▎        | 4/30 [03:15<20:42, 47.80s/it]

model train true


Thu 23:37:15,899 INF Training Started                                                                                                
Thu 23:37:17,835 INF Epoch 5 - Batch 1 - Train Loss: 4.521591663360596                                                               
Thu 23:37:18,684 INF Epoch 5 - Batch 2 - Train Loss: 4.526237964630127                                                               
Thu 23:37:19,943 INF Epoch 5 - Batch 3 - Train Loss: 4.573625087738037                                                               
Thu 23:37:20,762 INF Epoch 5 - Batch 4 - Train Loss: 4.554239749908447                                                               
Thu 23:37:21,640 INF Epoch 5 - Batch 5 - Train Loss: 4.517455101013184                                                               
Thu 23:37:22,467 INF Epoch 5 - Batch 6 - Train Loss: 4.642856597900391                                                               
Thu 23:37:23,272 INF Epoch 5 - Batch 7 - Train Loss: 4.5657215

lr =  0.01
model train false


Thu 23:37:51,718 INF Epoch 5 - Batch 32 - Val Loss: 4.609                                                                            
Thu 23:37:52,139 INF Epoch 5 - Batch 32 - Val Loss: 9.175                                                                            
Thu 23:37:52,691 INF Epoch 5 - Batch 32 - Val Loss: 13.751                                                                           
Thu 23:37:53,139 INF Epoch 5 - Batch 32 - Val Loss: 18.094                                                                           
Thu 23:37:53,545 INF Epoch 5 - Batch 32 - Val Loss: 22.728                                                                           
Thu 23:37:53,876 INF Epoch 5 - Batch 32 - Val Loss: 27.301                                                                           
Thu 23:37:54,244 INF Epoch 5 - Batch 32 - Val Loss: 31.892                                                                           
Thu 23:37:54,551 INF Epoch 5 - Batch 32 - Val Loss: 36.500    

tensor([91, 91, 91, 91, 91, 91, 91, 91, 32, 32, 32, 91, 91, 91, 91, 47, 32, 32,
        91, 91, 39, 91, 32, 91, 91, 91, 91, 91])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:38:04,650 INF Epoch 5 - Best Model Saved                                                                                      
 17%|█▋        | 5/30 [04:04<20:03, 48.14s/it]

model train true


Thu 23:38:04,655 INF Training Started                                                                                                
Thu 23:38:07,713 INF Epoch 6 - Batch 1 - Train Loss: 4.524312973022461                                                               
Thu 23:38:09,112 INF Epoch 6 - Batch 2 - Train Loss: 4.522811412811279                                                               
Thu 23:38:10,873 INF Epoch 6 - Batch 3 - Train Loss: 4.536117076873779                                                               
Thu 23:38:11,878 INF Epoch 6 - Batch 4 - Train Loss: 4.543949604034424                                                               
Thu 23:38:12,764 INF Epoch 6 - Batch 5 - Train Loss: 4.547751426696777                                                               
Thu 23:38:13,662 INF Epoch 6 - Batch 6 - Train Loss: 4.5357255935668945                                                              
Thu 23:38:14,580 INF Epoch 6 - Batch 7 - Train Loss: 4.5359191

lr =  0.01
model train false


Thu 23:38:44,112 INF Epoch 6 - Batch 32 - Val Loss: 4.614                                                                            
Thu 23:38:44,496 INF Epoch 6 - Batch 32 - Val Loss: 9.173                                                                            
Thu 23:38:44,797 INF Epoch 6 - Batch 32 - Val Loss: 13.812                                                                           
Thu 23:38:45,132 INF Epoch 6 - Batch 32 - Val Loss: 18.162                                                                           
Thu 23:38:45,401 INF Epoch 6 - Batch 32 - Val Loss: 22.410                                                                           
Thu 23:38:45,682 INF Epoch 6 - Batch 32 - Val Loss: 27.017                                                                           
Thu 23:38:45,961 INF Epoch 6 - Batch 32 - Val Loss: 31.595                                                                           
Thu 23:38:46,241 INF Epoch 6 - Batch 32 - Val Loss: 36.203    

tensor([28, 28, 28, 41, 41, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 41, 28,
        41, 28, 66, 41, 79, 66, 41, 66, 41, 41])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:38:54,760 INF Epoch 6 - Best Model Saved                                                                                      
 20%|██        | 6/30 [04:54<19:31, 48.81s/it]

model train true


Thu 23:38:54,776 INF Training Started                                                                                                
Thu 23:38:57,338 INF Epoch 7 - Batch 1 - Train Loss: 4.361260414123535                                                               
Thu 23:38:58,245 INF Epoch 7 - Batch 2 - Train Loss: 4.567569255828857                                                               
Thu 23:38:59,634 INF Epoch 7 - Batch 3 - Train Loss: 4.463656902313232                                                               
Thu 23:39:00,498 INF Epoch 7 - Batch 4 - Train Loss: 4.56459379196167                                                                
Thu 23:39:01,375 INF Epoch 7 - Batch 5 - Train Loss: 4.562589645385742                                                               
Thu 23:39:02,221 INF Epoch 7 - Batch 6 - Train Loss: 4.456327438354492                                                               
Thu 23:39:03,132 INF Epoch 7 - Batch 7 - Train Loss: 4.5365805

lr =  0.01
model train false


Thu 23:39:34,373 INF Epoch 7 - Batch 32 - Val Loss: 4.599                                                                            
Thu 23:39:34,718 INF Epoch 7 - Batch 32 - Val Loss: 10.039                                                                           
Thu 23:39:35,024 INF Epoch 7 - Batch 32 - Val Loss: 15.601                                                                           
Thu 23:39:35,367 INF Epoch 7 - Batch 32 - Val Loss: 19.870                                                                           
Thu 23:39:35,642 INF Epoch 7 - Batch 32 - Val Loss: 25.913                                                                           
Thu 23:39:35,917 INF Epoch 7 - Batch 32 - Val Loss: 30.416                                                                           
Thu 23:39:36,191 INF Epoch 7 - Batch 32 - Val Loss: 34.994                                                                           
Thu 23:39:36,462 INF Epoch 7 - Batch 32 - Val Loss: 43.727    

tensor([85, 85, 85, 85, 85,  4,  4, 85, 52, 85, 85, 85, 85, 85, 85, 85, 53, 85,
        85, 85, 85, 11, 85, 85,  4, 20, 59,  4])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 23%|██▎       | 7/30 [05:43<18:38, 48.63s/it]

model train true


Thu 23:39:43,064 INF Training Started                                                                                                
Thu 23:39:45,161 INF Epoch 8 - Batch 1 - Train Loss: 4.534938812255859                                                               
Thu 23:39:46,201 INF Epoch 8 - Batch 2 - Train Loss: 4.517330646514893                                                               
Thu 23:39:47,690 INF Epoch 8 - Batch 3 - Train Loss: 4.433328151702881                                                               
Thu 23:39:48,736 INF Epoch 8 - Batch 4 - Train Loss: 4.551388263702393                                                               
Thu 23:39:49,803 INF Epoch 8 - Batch 5 - Train Loss: 4.509462833404541                                                               
Thu 23:39:50,697 INF Epoch 8 - Batch 6 - Train Loss: 4.490053176879883                                                               
Thu 23:39:51,611 INF Epoch 8 - Batch 7 - Train Loss: 4.4872322

lr =  0.01
model train false


Thu 23:40:20,316 INF Epoch 8 - Batch 32 - Val Loss: 4.596                                                                            
Thu 23:40:20,675 INF Epoch 8 - Batch 32 - Val Loss: 8.929                                                                            
Thu 23:40:20,986 INF Epoch 8 - Batch 32 - Val Loss: 13.455                                                                           
Thu 23:40:21,381 INF Epoch 8 - Batch 32 - Val Loss: 17.657                                                                           
Thu 23:40:21,675 INF Epoch 8 - Batch 32 - Val Loss: 22.094                                                                           
Thu 23:40:22,045 INF Epoch 8 - Batch 32 - Val Loss: 26.684                                                                           
Thu 23:40:22,348 INF Epoch 8 - Batch 32 - Val Loss: 31.334                                                                           
Thu 23:40:22,618 INF Epoch 8 - Batch 32 - Val Loss: 35.989    

tensor([ 5,  9, 36, 36, 36, 36, 36, 36, 41, 41, 59, 36, 36, 36, 36, 36,  5, 36,
        41, 36, 58, 53,  5, 36, 53, 36, 36, 36])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 27%|██▋       | 8/30 [06:29<17:33, 47.91s/it]

model train true


Thu 23:40:29,424 INF Training Started                                                                                                
Thu 23:40:31,405 INF Epoch 9 - Batch 1 - Train Loss: 4.655386924743652                                                               
Thu 23:40:32,285 INF Epoch 9 - Batch 2 - Train Loss: 4.507771968841553                                                               
Thu 23:40:33,608 INF Epoch 9 - Batch 3 - Train Loss: 4.451326847076416                                                               
Thu 23:40:34,477 INF Epoch 9 - Batch 4 - Train Loss: 4.459765911102295                                                               
Thu 23:40:35,408 INF Epoch 9 - Batch 5 - Train Loss: 4.412693023681641                                                               
Thu 23:40:36,307 INF Epoch 9 - Batch 6 - Train Loss: 4.5310869216918945                                                              
Thu 23:40:37,167 INF Epoch 9 - Batch 7 - Train Loss: 4.4382152

lr =  0.01
model train false


Thu 23:41:05,936 INF Epoch 9 - Batch 32 - Val Loss: 4.601                                                                            
Thu 23:41:06,288 INF Epoch 9 - Batch 32 - Val Loss: 9.021                                                                            
Thu 23:41:06,591 INF Epoch 9 - Batch 32 - Val Loss: 13.523                                                                           
Thu 23:41:06,918 INF Epoch 9 - Batch 32 - Val Loss: 17.775                                                                           
Thu 23:41:07,213 INF Epoch 9 - Batch 32 - Val Loss: 21.850                                                                           
Thu 23:41:07,490 INF Epoch 9 - Batch 32 - Val Loss: 26.466                                                                           
Thu 23:41:07,782 INF Epoch 9 - Batch 32 - Val Loss: 30.993                                                                           
Thu 23:41:08,057 INF Epoch 9 - Batch 32 - Val Loss: 35.479    

tensor([36, 36, 41, 41, 46, 46, 49, 36, 36, 41, 36, 36, 41,  5, 36,  5,  5, 36,
        41, 36, 41, 41, 62, 36, 88, 41, 41, 41])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:41:15,901 INF Epoch 9 - Best Model Saved                                                                                      
 30%|███       | 9/30 [07:15<16:36, 47.48s/it]

model train true


Thu 23:41:15,918 INF Training Started                                                                                                
Thu 23:41:17,799 INF Epoch 10 - Batch 1 - Train Loss: 4.448310375213623                                                              
Thu 23:41:18,584 INF Epoch 10 - Batch 2 - Train Loss: 4.468269348144531                                                              
Thu 23:41:19,830 INF Epoch 10 - Batch 3 - Train Loss: 4.560635089874268                                                              
Thu 23:41:20,641 INF Epoch 10 - Batch 4 - Train Loss: 4.4633660316467285                                                             
Thu 23:41:21,443 INF Epoch 10 - Batch 5 - Train Loss: 4.360411643981934                                                              
Thu 23:41:22,273 INF Epoch 10 - Batch 6 - Train Loss: 4.4423298835754395                                                             
Thu 23:41:23,085 INF Epoch 10 - Batch 7 - Train Loss: 4.310092

lr =  0.01
model train false


Thu 23:41:51,545 INF Epoch 10 - Batch 32 - Val Loss: 4.547                                                                           
Thu 23:41:51,866 INF Epoch 10 - Batch 32 - Val Loss: 8.834                                                                           
Thu 23:41:52,174 INF Epoch 10 - Batch 32 - Val Loss: 13.320                                                                          
Thu 23:41:52,466 INF Epoch 10 - Batch 32 - Val Loss: 17.304                                                                          
Thu 23:41:52,731 INF Epoch 10 - Batch 32 - Val Loss: 22.408                                                                          
Thu 23:41:52,996 INF Epoch 10 - Batch 32 - Val Loss: 26.978                                                                          
Thu 23:41:53,258 INF Epoch 10 - Batch 32 - Val Loss: 31.491                                                                          
Thu 23:41:53,511 INF Epoch 10 - Batch 32 - Val Loss: 36.063   

tensor([55, 28, 11, 57, 57, 57, 85, 57, 28, 57, 85, 28, 85, 28, 57, 57, 57, 27,
        57, 28, 57, 55, 85, 28, 11, 28, 41, 57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 33%|███▎      | 10/30 [08:00<15:28, 46.42s/it]

model train true


Thu 23:41:59,997 INF Training Started                                                                                                
Thu 23:42:02,083 INF Epoch 11 - Batch 1 - Train Loss: 4.204257011413574                                                              
Thu 23:42:02,970 INF Epoch 11 - Batch 2 - Train Loss: 4.523696422576904                                                              
Thu 23:42:04,235 INF Epoch 11 - Batch 3 - Train Loss: 4.3248515129089355                                                             
Thu 23:42:05,082 INF Epoch 11 - Batch 4 - Train Loss: 4.476410865783691                                                              
Thu 23:42:05,946 INF Epoch 11 - Batch 5 - Train Loss: 4.485280990600586                                                              
Thu 23:42:06,851 INF Epoch 11 - Batch 6 - Train Loss: 4.405845642089844                                                              
Thu 23:42:07,766 INF Epoch 11 - Batch 7 - Train Loss: 4.478184

lr =  0.01
model train false


Thu 23:42:36,868 INF Epoch 11 - Batch 32 - Val Loss: 4.504                                                                           
Thu 23:42:37,196 INF Epoch 11 - Batch 32 - Val Loss: 8.761                                                                           
Thu 23:42:37,500 INF Epoch 11 - Batch 32 - Val Loss: 13.089                                                                          
Thu 23:42:37,811 INF Epoch 11 - Batch 32 - Val Loss: 17.343                                                                          
Thu 23:42:38,096 INF Epoch 11 - Batch 32 - Val Loss: 21.627                                                                          
Thu 23:42:38,366 INF Epoch 11 - Batch 32 - Val Loss: 25.987                                                                          
Thu 23:42:38,638 INF Epoch 11 - Batch 32 - Val Loss: 30.379                                                                          
Thu 23:42:38,956 INF Epoch 11 - Batch 32 - Val Loss: 34.914   

tensor([20, 64, 53, 41, 20, 31, 53, 62, 64, 31, 31, 31, 31, 31, 31, 31, 42, 31,
        20, 31, 64, 41, 64, 31, 41, 31, 64, 41])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:42:46,650 INF Epoch 11 - Best Model Saved                                                                                     
 37%|███▋      | 11/30 [08:46<14:43, 46.51s/it]

model train true


Thu 23:42:46,666 INF Training Started                                                                                                
Thu 23:42:48,658 INF Epoch 12 - Batch 1 - Train Loss: 4.2820892333984375                                                             
Thu 23:42:49,575 INF Epoch 12 - Batch 2 - Train Loss: 4.395565509796143                                                              
Thu 23:42:50,799 INF Epoch 12 - Batch 3 - Train Loss: 4.396618366241455                                                              
Thu 23:42:51,674 INF Epoch 12 - Batch 4 - Train Loss: 4.285853385925293                                                              
Thu 23:42:52,567 INF Epoch 12 - Batch 5 - Train Loss: 4.354033946990967                                                              
Thu 23:42:53,421 INF Epoch 12 - Batch 6 - Train Loss: 4.258074760437012                                                              
Thu 23:42:54,281 INF Epoch 12 - Batch 7 - Train Loss: 4.427338

lr =  0.01
model train false


Thu 23:43:24,148 INF Epoch 12 - Batch 32 - Val Loss: 4.588                                                                           
Thu 23:43:24,667 INF Epoch 12 - Batch 32 - Val Loss: 8.650                                                                           
Thu 23:43:25,088 INF Epoch 12 - Batch 32 - Val Loss: 13.025                                                                          
Thu 23:43:25,457 INF Epoch 12 - Batch 32 - Val Loss: 17.454                                                                          
Thu 23:43:25,776 INF Epoch 12 - Batch 32 - Val Loss: 21.254                                                                          
Thu 23:43:26,080 INF Epoch 12 - Batch 32 - Val Loss: 25.682                                                                          
Thu 23:43:26,399 INF Epoch 12 - Batch 32 - Val Loss: 30.055                                                                          
Thu 23:43:26,727 INF Epoch 12 - Batch 32 - Val Loss: 34.640   

tensor([31, 82, 15, 72, 15, 31, 31, 31, 31, 58, 82, 58, 58, 58, 31, 31, 25, 31,
        82, 31, 58, 82, 82,  9, 58, 31, 82, 58])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 40%|████      | 12/30 [09:33<14:00, 46.72s/it]

model train true


Thu 23:43:33,916 INF Training Started                                                                                                
Thu 23:43:36,017 INF Epoch 13 - Batch 1 - Train Loss: 4.394881248474121                                                              
Thu 23:43:36,972 INF Epoch 13 - Batch 2 - Train Loss: 4.289019584655762                                                              
Thu 23:43:38,291 INF Epoch 13 - Batch 3 - Train Loss: 4.282024383544922                                                              
Thu 23:43:39,295 INF Epoch 13 - Batch 4 - Train Loss: 4.300741195678711                                                              
Thu 23:43:40,278 INF Epoch 13 - Batch 5 - Train Loss: 4.355500221252441                                                              
Thu 23:43:41,556 INF Epoch 13 - Batch 6 - Train Loss: 4.340766429901123                                                              
Thu 23:43:42,762 INF Epoch 13 - Batch 7 - Train Loss: 4.349847

lr =  0.01
model train false


Thu 23:44:12,292 INF Epoch 13 - Batch 32 - Val Loss: 4.282                                                                           
Thu 23:44:12,631 INF Epoch 13 - Batch 32 - Val Loss: 8.401                                                                           
Thu 23:44:12,969 INF Epoch 13 - Batch 32 - Val Loss: 12.868                                                                          
Thu 23:44:13,328 INF Epoch 13 - Batch 32 - Val Loss: 16.870                                                                          
Thu 23:44:13,610 INF Epoch 13 - Batch 32 - Val Loss: 21.142                                                                          
Thu 23:44:13,909 INF Epoch 13 - Batch 32 - Val Loss: 26.283                                                                          
Thu 23:44:14,207 INF Epoch 13 - Batch 32 - Val Loss: 30.426                                                                          
Thu 23:44:14,507 INF Epoch 13 - Batch 32 - Val Loss: 35.146   

tensor([80, 59, 49, 18, 57, 18, 49, 58, 58, 73, 58, 57, 73, 80, 59, 59, 58, 15,
        90, 90, 58, 58, 73, 90, 58,  3, 59, 58])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 43%|████▎     | 13/30 [10:21<13:17, 46.91s/it]

model train true


Thu 23:44:21,270 INF Training Started                                                                                                
Thu 23:44:23,350 INF Epoch 14 - Batch 1 - Train Loss: 4.270017147064209                                                              
Thu 23:44:24,334 INF Epoch 14 - Batch 2 - Train Loss: 4.1207380294799805                                                             
Thu 23:44:25,749 INF Epoch 14 - Batch 3 - Train Loss: 4.212217330932617                                                              
Thu 23:44:26,601 INF Epoch 14 - Batch 4 - Train Loss: 4.193364143371582                                                              
Thu 23:44:27,541 INF Epoch 14 - Batch 5 - Train Loss: 4.534080982208252                                                              
Thu 23:44:28,478 INF Epoch 14 - Batch 6 - Train Loss: 4.182155132293701                                                              
Thu 23:44:29,373 INF Epoch 14 - Batch 7 - Train Loss: 4.234309

lr =  0.01
model train false


Thu 23:44:59,462 INF Epoch 14 - Batch 32 - Val Loss: 4.374                                                                           
Thu 23:44:59,802 INF Epoch 14 - Batch 32 - Val Loss: 8.589                                                                           
Thu 23:45:00,106 INF Epoch 14 - Batch 32 - Val Loss: 12.924                                                                          
Thu 23:45:00,454 INF Epoch 14 - Batch 32 - Val Loss: 18.494                                                                          
Thu 23:45:00,727 INF Epoch 14 - Batch 32 - Val Loss: 25.115                                                                          
Thu 23:45:01,022 INF Epoch 14 - Batch 32 - Val Loss: 29.497                                                                          
Thu 23:45:01,304 INF Epoch 14 - Batch 32 - Val Loss: 33.639                                                                          
Thu 23:45:01,578 INF Epoch 14 - Batch 32 - Val Loss: 37.874   

tensor([25, 25, 20, 57, 41, 20, 84, 20, 57, 57, 95, 57, 25, 20, 20, 57, 26, 26,
        57, 28, 57, 26, 99, 20, 41, 68, 57, 25])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 47%|████▋     | 14/30 [11:08<12:30, 46.92s/it]

model train true


Thu 23:45:08,197 INF Training Started                                                                                                
Thu 23:45:10,255 INF Epoch 15 - Batch 1 - Train Loss: 4.239264011383057                                                              
Thu 23:45:11,176 INF Epoch 15 - Batch 2 - Train Loss: 4.164328098297119                                                              
Thu 23:45:12,759 INF Epoch 15 - Batch 3 - Train Loss: 4.400548934936523                                                              
Thu 23:45:13,639 INF Epoch 15 - Batch 4 - Train Loss: 4.3081793785095215                                                             
Thu 23:45:14,505 INF Epoch 15 - Batch 5 - Train Loss: 4.26188850402832                                                               
Thu 23:45:15,367 INF Epoch 15 - Batch 6 - Train Loss: 4.390083312988281                                                              
Thu 23:45:16,224 INF Epoch 15 - Batch 7 - Train Loss: 4.199515

lr =  0.01
model train false


Thu 23:45:45,264 INF Epoch 15 - Batch 32 - Val Loss: 4.430                                                                           
Thu 23:45:45,663 INF Epoch 15 - Batch 32 - Val Loss: 9.288                                                                           
Thu 23:45:45,968 INF Epoch 15 - Batch 32 - Val Loss: 13.418                                                                          
Thu 23:45:46,282 INF Epoch 15 - Batch 32 - Val Loss: 17.656                                                                          
Thu 23:45:46,569 INF Epoch 15 - Batch 32 - Val Loss: 21.968                                                                          
Thu 23:45:46,846 INF Epoch 15 - Batch 32 - Val Loss: 26.286                                                                          
Thu 23:45:47,113 INF Epoch 15 - Batch 32 - Val Loss: 30.511                                                                          
Thu 23:45:47,387 INF Epoch 15 - Batch 32 - Val Loss: 34.760   

tensor([99,  5, 15, 69, 70, 72, 70, 57, 58, 49, 57,  5, 57, 69, 49, 57,  5, 57,
        72, 97, 57, 49, 57, 69, 70, 16, 72, 57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:45:55,568 INF Epoch 15 - Best Model Saved                                                                                     
 50%|█████     | 15/30 [11:55<11:46, 47.07s/it]

model train true


Thu 23:45:55,584 INF Training Started                                                                                                
Thu 23:45:57,904 INF Epoch 16 - Batch 1 - Train Loss: 4.326566696166992                                                              
Thu 23:45:59,207 INF Epoch 16 - Batch 2 - Train Loss: 4.217896938323975                                                              
Thu 23:46:00,576 INF Epoch 16 - Batch 3 - Train Loss: 4.237682342529297                                                              
Thu 23:46:01,471 INF Epoch 16 - Batch 4 - Train Loss: 4.375143527984619                                                              
Thu 23:46:02,348 INF Epoch 16 - Batch 5 - Train Loss: 4.016290664672852                                                              
Thu 23:46:03,198 INF Epoch 16 - Batch 6 - Train Loss: 4.343782424926758                                                              
Thu 23:46:04,053 INF Epoch 16 - Batch 7 - Train Loss: 4.262582

lr =  0.01
model train false


Thu 23:46:33,614 INF Epoch 16 - Batch 32 - Val Loss: 4.471                                                                           
Thu 23:46:33,956 INF Epoch 16 - Batch 32 - Val Loss: 9.263                                                                           
Thu 23:46:34,272 INF Epoch 16 - Batch 32 - Val Loss: 13.415                                                                          
Thu 23:46:34,607 INF Epoch 16 - Batch 32 - Val Loss: 17.458                                                                          
Thu 23:46:34,877 INF Epoch 16 - Batch 32 - Val Loss: 21.717                                                                          
Thu 23:46:35,152 INF Epoch 16 - Batch 32 - Val Loss: 26.220                                                                          
Thu 23:46:35,440 INF Epoch 16 - Batch 32 - Val Loss: 30.321                                                                          
Thu 23:46:35,723 INF Epoch 16 - Batch 32 - Val Loss: 34.522   

tensor([25, 80, 57, 57, 25, 30, 25, 79, 57, 73, 57, 57, 30, 73, 73, 57, 57, 57,
        79, 65, 57, 49, 30, 57, 11, 57, 57, 57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:46:44,078 INF Epoch 16 - Best Model Saved                                                                                     
 53%|█████▎    | 16/30 [12:44<11:05, 47.50s/it]

model train true


Thu 23:46:44,094 INF Training Started                                                                                                
Thu 23:46:46,103 INF Epoch 17 - Batch 1 - Train Loss: 3.9958698749542236                                                             
Thu 23:46:46,891 INF Epoch 17 - Batch 2 - Train Loss: 4.326188564300537                                                              
Thu 23:46:48,005 INF Epoch 17 - Batch 3 - Train Loss: 4.105600833892822                                                              
Thu 23:46:48,894 INF Epoch 17 - Batch 4 - Train Loss: 4.080204963684082                                                              
Thu 23:46:49,835 INF Epoch 17 - Batch 5 - Train Loss: 4.050545692443848                                                              
Thu 23:46:50,698 INF Epoch 17 - Batch 6 - Train Loss: 4.670936107635498                                                              
Thu 23:46:51,570 INF Epoch 17 - Batch 7 - Train Loss: 4.218925

lr =  0.01
model train false


Thu 23:47:22,464 INF Epoch 17 - Batch 32 - Val Loss: 4.494                                                                           
Thu 23:47:22,887 INF Epoch 17 - Batch 32 - Val Loss: 8.604                                                                           
Thu 23:47:23,230 INF Epoch 17 - Batch 32 - Val Loss: 12.846                                                                          
Thu 23:47:23,570 INF Epoch 17 - Batch 32 - Val Loss: 16.964                                                                          
Thu 23:47:23,858 INF Epoch 17 - Batch 32 - Val Loss: 20.917                                                                          
Thu 23:47:24,154 INF Epoch 17 - Batch 32 - Val Loss: 25.224                                                                          
Thu 23:47:24,453 INF Epoch 17 - Batch 32 - Val Loss: 29.390                                                                          
Thu 23:47:24,756 INF Epoch 17 - Batch 32 - Val Loss: 33.556   

tensor([ 5,  5,  5, 15, 62, 55, 43,  5,  5,  5, 54,  5,  5,  5, 55, 25,  5, 12,
         5, 69,  5,  5, 62, 60, 53,  5, 58,  5])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:47:33,363 INF Epoch 17 - Best Model Saved                                                                                     
 57%|█████▋    | 17/30 [13:33<10:24, 48.04s/it]

model train true


Thu 23:47:33,381 INF Training Started                                                                                                
Thu 23:47:35,593 INF Epoch 18 - Batch 1 - Train Loss: 4.221996784210205                                                              
Thu 23:47:36,580 INF Epoch 18 - Batch 2 - Train Loss: 4.468770503997803                                                              
Thu 23:47:37,896 INF Epoch 18 - Batch 3 - Train Loss: 4.206066131591797                                                              
Thu 23:47:38,870 INF Epoch 18 - Batch 4 - Train Loss: 4.133763313293457                                                              
Thu 23:47:39,829 INF Epoch 18 - Batch 5 - Train Loss: 4.108038902282715                                                              
Thu 23:47:40,787 INF Epoch 18 - Batch 6 - Train Loss: 4.177576065063477                                                              
Thu 23:47:41,755 INF Epoch 18 - Batch 7 - Train Loss: 3.980270

lr =  0.01
model train false


Thu 23:48:16,764 INF Epoch 18 - Batch 32 - Val Loss: 4.268                                                                           
Thu 23:48:17,082 INF Epoch 18 - Batch 32 - Val Loss: 8.493                                                                           
Thu 23:48:17,401 INF Epoch 18 - Batch 32 - Val Loss: 12.750                                                                          
Thu 23:48:17,694 INF Epoch 18 - Batch 32 - Val Loss: 16.935                                                                          
Thu 23:48:18,005 INF Epoch 18 - Batch 32 - Val Loss: 21.080                                                                          
Thu 23:48:18,286 INF Epoch 18 - Batch 32 - Val Loss: 25.182                                                                          
Thu 23:48:18,576 INF Epoch 18 - Batch 32 - Val Loss: 29.180                                                                          
Thu 23:48:18,878 INF Epoch 18 - Batch 32 - Val Loss: 33.198   

tensor([ 25,  57,  53,  25,  57,  57,  25,  88,  58,  57,  57,  88,  57, 101,
         57,  88,  88,  49,  57,  77,  20,  57,   1,  20,  57,   5,  58,  58])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:48:28,962 INF Epoch 18 - Best Model Saved                                                                                     
 60%|██████    | 18/30 [14:29<10:03, 50.31s/it]

model train true


Thu 23:48:28,979 INF Training Started                                                                                                
Thu 23:48:30,949 INF Epoch 19 - Batch 1 - Train Loss: 3.9367482662200928                                                             
Thu 23:48:31,848 INF Epoch 19 - Batch 2 - Train Loss: 4.268521785736084                                                              
Thu 23:48:33,021 INF Epoch 19 - Batch 3 - Train Loss: 4.017881870269775                                                              
Thu 23:48:33,913 INF Epoch 19 - Batch 4 - Train Loss: 4.051877975463867                                                              
Thu 23:48:34,831 INF Epoch 19 - Batch 5 - Train Loss: 4.332213401794434                                                              
Thu 23:48:35,697 INF Epoch 19 - Batch 6 - Train Loss: 4.261078834533691                                                              
Thu 23:48:36,574 INF Epoch 19 - Batch 7 - Train Loss: 4.050568

lr =  0.01
model train false


Thu 23:49:04,625 INF Epoch 19 - Batch 32 - Val Loss: 4.491                                                                           
Thu 23:49:04,961 INF Epoch 19 - Batch 32 - Val Loss: 8.681                                                                           
Thu 23:49:05,302 INF Epoch 19 - Batch 32 - Val Loss: 12.947                                                                          
Thu 23:49:05,709 INF Epoch 19 - Batch 32 - Val Loss: 17.186                                                                          
Thu 23:49:06,086 INF Epoch 19 - Batch 32 - Val Loss: 21.459                                                                          
Thu 23:49:06,455 INF Epoch 19 - Batch 32 - Val Loss: 25.666                                                                          
Thu 23:49:06,793 INF Epoch 19 - Batch 32 - Val Loss: 29.859                                                                          
Thu 23:49:07,075 INF Epoch 19 - Batch 32 - Val Loss: 34.079   

tensor([25, 60, 60, 25, 47,  5, 25, 25, 57, 60, 54, 60, 60, 57, 60, 60, 58, 60,
        57, 60, 55, 57, 45, 60, 25, 60, 58, 57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 63%|██████▎   | 19/30 [15:13<08:54, 48.56s/it]

model train true


Thu 23:49:13,501 INF Training Started                                                                                                
Thu 23:49:15,437 INF Epoch 20 - Batch 1 - Train Loss: 3.8984484672546387                                                             
Thu 23:49:16,305 INF Epoch 20 - Batch 2 - Train Loss: 3.896775722503662                                                              
Thu 23:49:17,590 INF Epoch 20 - Batch 3 - Train Loss: 3.9369993209838867                                                             
Thu 23:49:18,595 INF Epoch 20 - Batch 4 - Train Loss: 4.372199535369873                                                              
Thu 23:49:19,621 INF Epoch 20 - Batch 5 - Train Loss: 4.181512355804443                                                              
Thu 23:49:20,509 INF Epoch 20 - Batch 6 - Train Loss: 4.017248153686523                                                              
Thu 23:49:21,363 INF Epoch 20 - Batch 7 - Train Loss: 3.966815

lr =  0.01
model train false


Thu 23:49:50,578 INF Epoch 20 - Batch 32 - Val Loss: 4.186                                                                           
Thu 23:49:50,916 INF Epoch 20 - Batch 32 - Val Loss: 8.082                                                                           
Thu 23:49:51,251 INF Epoch 20 - Batch 32 - Val Loss: 11.985                                                                          
Thu 23:49:51,561 INF Epoch 20 - Batch 32 - Val Loss: 15.880                                                                          
Thu 23:49:51,850 INF Epoch 20 - Batch 32 - Val Loss: 19.889                                                                          
Thu 23:49:52,136 INF Epoch 20 - Batch 32 - Val Loss: 24.092                                                                          
Thu 23:49:52,414 INF Epoch 20 - Batch 32 - Val Loss: 27.987                                                                          
Thu 23:49:52,754 INF Epoch 20 - Batch 32 - Val Loss: 32.154   

tensor([25, 96, 25, 53, 25, 96, 53, 96, 20, 62, 87, 84, 57, 96, 96,  5, 62, 62,
        80, 61, 57, 62, 25, 87, 53, 87, 58, 57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:50:01,477 INF Epoch 20 - Best Model Saved                                                                                     
 67%|██████▋   | 20/30 [16:01<08:04, 48.40s/it]

model train true


Thu 23:50:01,491 INF Training Started                                                                                                
Thu 23:50:03,628 INF Epoch 21 - Batch 1 - Train Loss: 4.0827131271362305                                                             
Thu 23:50:04,614 INF Epoch 21 - Batch 2 - Train Loss: 4.136758327484131                                                              
Thu 23:50:05,921 INF Epoch 21 - Batch 3 - Train Loss: 4.069881916046143                                                              
Thu 23:50:06,773 INF Epoch 21 - Batch 4 - Train Loss: 4.297147274017334                                                              
Thu 23:50:07,635 INF Epoch 21 - Batch 5 - Train Loss: 4.319617748260498                                                              
Thu 23:50:08,480 INF Epoch 21 - Batch 6 - Train Loss: 4.163552761077881                                                              
Thu 23:50:09,331 INF Epoch 21 - Batch 7 - Train Loss: 4.190396

lr =  0.01
model train false


Thu 23:50:39,226 INF Epoch 21 - Batch 32 - Val Loss: 4.749                                                                           
Thu 23:50:39,583 INF Epoch 21 - Batch 32 - Val Loss: 14.320                                                                          
Thu 23:50:39,926 INF Epoch 21 - Batch 32 - Val Loss: 18.636                                                                          
Thu 23:50:40,247 INF Epoch 21 - Batch 32 - Val Loss: 23.086                                                                          
Thu 23:50:40,525 INF Epoch 21 - Batch 32 - Val Loss: 29.384                                                                          
Thu 23:50:40,787 INF Epoch 21 - Batch 32 - Val Loss: 34.672                                                                          
Thu 23:50:41,064 INF Epoch 21 - Batch 32 - Val Loss: 38.904                                                                          
Thu 23:50:41,396 INF Epoch 21 - Batch 32 - Val Loss: 43.060   

tensor([ 25,  43,  25,  53,  53,  49,  55,  43,  72,  25,   5,  84,  57,   5,
         55,  25,  53, 100,   5,  84,  49,  49,  55,  84,  25,  43,  72,  46])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 70%|███████   | 21/30 [16:48<07:11, 47.93s/it]

model train true


Thu 23:50:48,380 INF Training Started                                                                                                
Thu 23:50:50,627 INF Epoch 22 - Batch 1 - Train Loss: 4.124053001403809                                                              
Thu 23:50:51,580 INF Epoch 22 - Batch 2 - Train Loss: 4.069553852081299                                                              
Thu 23:50:52,968 INF Epoch 22 - Batch 3 - Train Loss: 3.9568886756896973                                                             
Thu 23:50:53,805 INF Epoch 22 - Batch 4 - Train Loss: 4.041374683380127                                                              
Thu 23:50:54,758 INF Epoch 22 - Batch 5 - Train Loss: 3.899299144744873                                                              
Thu 23:50:55,657 INF Epoch 22 - Batch 6 - Train Loss: 3.9513349533081055                                                             
Thu 23:50:56,534 INF Epoch 22 - Batch 7 - Train Loss: 4.039926

lr =  0.01
model train false


Thu 23:51:27,123 INF Epoch 22 - Batch 32 - Val Loss: 4.224                                                                           
Thu 23:51:27,504 INF Epoch 22 - Batch 32 - Val Loss: 7.972                                                                           
Thu 23:51:28,025 INF Epoch 22 - Batch 32 - Val Loss: 11.984                                                                          
Thu 23:51:28,297 INF Epoch 22 - Batch 32 - Val Loss: 16.343                                                                          
Thu 23:51:28,594 INF Epoch 22 - Batch 32 - Val Loss: 20.388                                                                          
Thu 23:51:28,868 INF Epoch 22 - Batch 32 - Val Loss: 24.551                                                                          
Thu 23:51:29,213 INF Epoch 22 - Batch 32 - Val Loss: 28.218                                                                          
Thu 23:51:29,536 INF Epoch 22 - Batch 32 - Val Loss: 32.158   

tensor([25, 87, 53, 53, 25, 57, 25, 57, 57, 57,  5, 16, 57,  7,  5, 57, 57, 57,
        57, 48,  5, 49, 25, 87, 62, 77, 57, 57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:51:38,320 INF Epoch 22 - Best Model Saved                                                                                     
 73%|███████▎  | 22/30 [17:38<06:28, 48.56s/it]

model train true


Thu 23:51:38,335 INF Training Started                                                                                                
Thu 23:51:40,542 INF Epoch 23 - Batch 1 - Train Loss: 3.972792625427246                                                              
Thu 23:51:41,531 INF Epoch 23 - Batch 2 - Train Loss: 3.865950345993042                                                              
Thu 23:51:42,969 INF Epoch 23 - Batch 3 - Train Loss: 4.3278374671936035                                                             
Thu 23:51:43,829 INF Epoch 23 - Batch 4 - Train Loss: 4.111372470855713                                                              
Thu 23:51:44,675 INF Epoch 23 - Batch 5 - Train Loss: 4.148685455322266                                                              
Thu 23:51:45,552 INF Epoch 23 - Batch 6 - Train Loss: 3.9099512100219727                                                             
Thu 23:51:46,458 INF Epoch 23 - Batch 7 - Train Loss: 4.066957

lr =  0.01
model train false


Thu 23:52:17,567 INF Epoch 23 - Batch 32 - Val Loss: 4.540                                                                           
Thu 23:52:17,894 INF Epoch 23 - Batch 32 - Val Loss: 8.901                                                                           
Thu 23:52:18,229 INF Epoch 23 - Batch 32 - Val Loss: 12.859                                                                          
Thu 23:52:18,548 INF Epoch 23 - Batch 32 - Val Loss: 16.827                                                                          
Thu 23:52:18,800 INF Epoch 23 - Batch 32 - Val Loss: 21.085                                                                          
Thu 23:52:19,092 INF Epoch 23 - Batch 32 - Val Loss: 25.492                                                                          
Thu 23:52:19,362 INF Epoch 23 - Batch 32 - Val Loss: 29.608                                                                          
Thu 23:52:19,638 INF Epoch 23 - Batch 32 - Val Loss: 34.192   

tensor([ 54,  25,  25, 100,  53,  99,  53,  60,  39,  85,  60,  60,  60,  60,
         59,  60,  60,  60,  58,  39,  60,  26,  25,  59,  45,  60,  59,  25])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 77%|███████▋  | 23/30 [18:26<05:38, 48.36s/it]

model train true


Thu 23:52:26,288 INF Training Started                                                                                                
Thu 23:52:28,518 INF Epoch 24 - Batch 1 - Train Loss: 3.868370294570923                                                              
Thu 23:52:29,438 INF Epoch 24 - Batch 2 - Train Loss: 3.943849802017212                                                              
Thu 23:52:30,879 INF Epoch 24 - Batch 3 - Train Loss: 3.8782966136932373                                                             
Thu 23:52:31,727 INF Epoch 24 - Batch 4 - Train Loss: 4.013034820556641                                                              
Thu 23:52:32,835 INF Epoch 24 - Batch 5 - Train Loss: 3.9756722450256348                                                             
Thu 23:52:33,918 INF Epoch 24 - Batch 6 - Train Loss: 4.269196033477783                                                              
Thu 23:52:35,107 INF Epoch 24 - Batch 7 - Train Loss: 3.972550

lr =  0.01
model train false


Thu 23:53:04,581 INF Epoch 24 - Batch 32 - Val Loss: 3.908                                                                           
Thu 23:53:04,947 INF Epoch 24 - Batch 32 - Val Loss: 7.619                                                                           
Thu 23:53:05,237 INF Epoch 24 - Batch 32 - Val Loss: 11.731                                                                          
Thu 23:53:05,559 INF Epoch 24 - Batch 32 - Val Loss: 15.957                                                                          
Thu 23:53:05,837 INF Epoch 24 - Batch 32 - Val Loss: 19.907                                                                          
Thu 23:53:06,115 INF Epoch 24 - Batch 32 - Val Loss: 23.808                                                                          
Thu 23:53:06,384 INF Epoch 24 - Batch 32 - Val Loss: 27.780                                                                          
Thu 23:53:06,647 INF Epoch 24 - Batch 32 - Val Loss: 31.684   

tensor([ 62, 100,  53, 100,  53,  71,  62,  62,  69,  43,  92,  71, 100,  58,
         58, 100,  58, 100,  20,  63, 100,  58,  25,  16,   4,  20,   7,  70])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 80%|████████  | 24/30 [19:13<04:47, 47.99s/it]

model train true


Thu 23:53:13,414 INF Training Started                                                                                                
Thu 23:53:15,623 INF Epoch 25 - Batch 1 - Train Loss: 3.996093273162842                                                              
Thu 23:53:16,524 INF Epoch 25 - Batch 2 - Train Loss: 4.174770355224609                                                              
Thu 23:53:17,886 INF Epoch 25 - Batch 3 - Train Loss: 3.88030743598938                                                               
Thu 23:53:18,732 INF Epoch 25 - Batch 4 - Train Loss: 3.9908199310302734                                                             
Thu 23:53:19,569 INF Epoch 25 - Batch 5 - Train Loss: 3.960677146911621                                                              
Thu 23:53:20,466 INF Epoch 25 - Batch 6 - Train Loss: 3.9728543758392334                                                             
Thu 23:53:21,350 INF Epoch 25 - Batch 7 - Train Loss: 3.972383

lr =  0.01
model train false


Thu 23:53:51,506 INF Epoch 25 - Batch 32 - Val Loss: 4.325                                                                           
Thu 23:53:51,962 INF Epoch 25 - Batch 32 - Val Loss: 8.630                                                                           
Thu 23:53:52,235 INF Epoch 25 - Batch 32 - Val Loss: 12.516                                                                          
Thu 23:53:52,505 INF Epoch 25 - Batch 32 - Val Loss: 16.573                                                                          
Thu 23:53:52,759 INF Epoch 25 - Batch 32 - Val Loss: 20.553                                                                          
Thu 23:53:53,035 INF Epoch 25 - Batch 32 - Val Loss: 24.330                                                                          
Thu 23:53:53,304 INF Epoch 25 - Batch 32 - Val Loss: 28.602                                                                          
Thu 23:53:53,567 INF Epoch 25 - Batch 32 - Val Loss: 32.390   

tensor([25, 62, 16, 25, 46, 43, 25, 99, 72, 93, 43, 43, 99, 59, 57, 25, 25, 55,
        20,  1, 20, 58, 25, 20, 62, 79, 20, 58])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:54:01,705 INF Epoch 25 - Best Model Saved                                                                                     
 83%|████████▎ | 25/30 [20:01<04:00, 48.10s/it]

model train true


Thu 23:54:01,721 INF Training Started                                                                                                
Thu 23:54:03,890 INF Epoch 26 - Batch 1 - Train Loss: 4.189918518066406                                                              
Thu 23:54:04,752 INF Epoch 26 - Batch 2 - Train Loss: 3.601745843887329                                                              
Thu 23:54:06,166 INF Epoch 26 - Batch 3 - Train Loss: 3.8185598850250244                                                             
Thu 23:54:07,062 INF Epoch 26 - Batch 4 - Train Loss: 3.8384125232696533                                                             
Thu 23:54:07,874 INF Epoch 26 - Batch 5 - Train Loss: 3.978518009185791                                                              
Thu 23:54:08,733 INF Epoch 26 - Batch 6 - Train Loss: 3.9688210487365723                                                             
Thu 23:54:09,630 INF Epoch 26 - Batch 7 - Train Loss: 3.816844

lr =  0.01
model train false


Thu 23:54:41,424 INF Epoch 26 - Batch 32 - Val Loss: 4.112                                                                           
Thu 23:54:41,757 INF Epoch 26 - Batch 32 - Val Loss: 7.655                                                                           
Thu 23:54:42,032 INF Epoch 26 - Batch 32 - Val Loss: 11.695                                                                          
Thu 23:54:42,289 INF Epoch 26 - Batch 32 - Val Loss: 15.708                                                                          
Thu 23:54:42,555 INF Epoch 26 - Batch 32 - Val Loss: 19.886                                                                          
Thu 23:54:42,817 INF Epoch 26 - Batch 32 - Val Loss: 24.195                                                                          
Thu 23:54:43,066 INF Epoch 26 - Batch 32 - Val Loss: 28.391                                                                          
Thu 23:54:43,268 INF Epoch 26 - Batch 32 - Val Loss: 32.700   

tensor([10, 55, 25, 60, 53, 60, 57, 60, 68, 60, 25, 60, 49, 60, 64, 90, 57, 60,
        58,  2, 57, 58, 53, 57, 53, 60, 58, 64])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 87%|████████▋ | 26/30 [20:50<03:13, 48.37s/it]

model train true


Thu 23:54:50,799 INF Training Started                                                                                                
Thu 23:54:53,253 INF Epoch 27 - Batch 1 - Train Loss: 4.113705635070801                                                              
Thu 23:54:54,176 INF Epoch 27 - Batch 2 - Train Loss: 3.6431498527526855                                                             
Thu 23:54:55,596 INF Epoch 27 - Batch 3 - Train Loss: 3.9814064502716064                                                             
Thu 23:54:56,502 INF Epoch 27 - Batch 4 - Train Loss: 3.860149621963501                                                              
Thu 23:54:57,409 INF Epoch 27 - Batch 5 - Train Loss: 3.9035332202911377                                                             
Thu 23:54:58,264 INF Epoch 27 - Batch 6 - Train Loss: 3.5523221492767334                                                             
Thu 23:54:59,115 INF Epoch 27 - Batch 7 - Train Loss: 3.618569

lr =  0.01
model train false


Thu 23:55:29,269 INF Epoch 27 - Batch 32 - Val Loss: 4.078                                                                           
Thu 23:55:29,682 INF Epoch 27 - Batch 32 - Val Loss: 8.363                                                                           
Thu 23:55:29,945 INF Epoch 27 - Batch 32 - Val Loss: 11.936                                                                          
Thu 23:55:30,250 INF Epoch 27 - Batch 32 - Val Loss: 15.836                                                                          
Thu 23:55:30,529 INF Epoch 27 - Batch 32 - Val Loss: 19.962                                                                          
Thu 23:55:30,783 INF Epoch 27 - Batch 32 - Val Loss: 24.081                                                                          
Thu 23:55:31,105 INF Epoch 27 - Batch 32 - Val Loss: 28.027                                                                          
Thu 23:55:31,398 INF Epoch 27 - Batch 32 - Val Loss: 32.071   

tensor([ 25,  55,  25,  55,  25, 100,   4, 100,  20,  43,  57,  43,  25,  87,
         70,  25,  25,  70,  57,  31,  25,  26,  25,  43,   4,  12,  58,  57])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 90%|█████████ | 27/30 [21:38<02:24, 48.19s/it]

model train true


Thu 23:55:38,556 INF Training Started                                                                                                
Thu 23:55:40,936 INF Epoch 28 - Batch 1 - Train Loss: 3.7747244834899902                                                             
Thu 23:55:41,852 INF Epoch 28 - Batch 2 - Train Loss: 3.7233335971832275                                                             
Thu 23:55:43,445 INF Epoch 28 - Batch 3 - Train Loss: 4.047811508178711                                                              
Thu 23:55:44,284 INF Epoch 28 - Batch 4 - Train Loss: 3.922642707824707                                                              
Thu 23:55:45,134 INF Epoch 28 - Batch 5 - Train Loss: 4.041444778442383                                                              
Thu 23:55:46,029 INF Epoch 28 - Batch 6 - Train Loss: 3.667799711227417                                                              
Thu 23:55:46,970 INF Epoch 28 - Batch 7 - Train Loss: 4.112799

lr =  0.01
model train false


Thu 23:56:17,260 INF Epoch 28 - Batch 32 - Val Loss: 4.108                                                                           
Thu 23:56:17,758 INF Epoch 28 - Batch 32 - Val Loss: 8.464                                                                           
Thu 23:56:18,129 INF Epoch 28 - Batch 32 - Val Loss: 12.351                                                                          
Thu 23:56:18,487 INF Epoch 28 - Batch 32 - Val Loss: 16.162                                                                          
Thu 23:56:18,826 INF Epoch 28 - Batch 32 - Val Loss: 20.039                                                                          
Thu 23:56:19,171 INF Epoch 28 - Batch 32 - Val Loss: 24.234                                                                          
Thu 23:56:19,471 INF Epoch 28 - Batch 32 - Val Loss: 28.135                                                                          
Thu 23:56:19,880 INF Epoch 28 - Batch 32 - Val Loss: 31.621   

tensor([53, 54, 53, 60, 99, 57, 55, 60, 48, 53, 96, 22, 55, 96, 96, 53, 99, 60,
        58,  1, 96, 57, 55, 60, 53, 55, 41, 15])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Thu 23:56:28,298 INF Epoch 28 - Best Model Saved                                                                                     
 93%|█████████▎| 28/30 [22:28<01:37, 48.68s/it]

model train true


Thu 23:56:28,321 INF Training Started                                                                                                
Thu 23:56:30,614 INF Epoch 29 - Batch 1 - Train Loss: 3.871077060699463                                                              
Thu 23:56:31,558 INF Epoch 29 - Batch 2 - Train Loss: 3.8203935623168945                                                             
Thu 23:56:34,024 INF Epoch 29 - Batch 3 - Train Loss: 3.9649717807769775                                                             
Thu 23:56:34,984 INF Epoch 29 - Batch 4 - Train Loss: 3.8262405395507812                                                             
Thu 23:56:35,821 INF Epoch 29 - Batch 5 - Train Loss: 4.063276290893555                                                              
Thu 23:56:36,785 INF Epoch 29 - Batch 6 - Train Loss: 3.94680118560791                                                               
Thu 23:56:37,642 INF Epoch 29 - Batch 7 - Train Loss: 3.935689

lr =  0.01
model train false


Thu 23:57:07,020 INF Epoch 29 - Batch 32 - Val Loss: 3.879                                                                           
Thu 23:57:07,277 INF Epoch 29 - Batch 32 - Val Loss: 12.919                                                                          
Thu 23:57:07,523 INF Epoch 29 - Batch 32 - Val Loss: 16.371                                                                          
Thu 23:57:07,780 INF Epoch 29 - Batch 32 - Val Loss: 19.853                                                                          
Thu 23:57:08,033 INF Epoch 29 - Batch 32 - Val Loss: 25.210                                                                          
Thu 23:57:08,287 INF Epoch 29 - Batch 32 - Val Loss: 29.607                                                                          
Thu 23:57:08,533 INF Epoch 29 - Batch 32 - Val Loss: 33.596                                                                          
Thu 23:57:08,784 INF Epoch 29 - Batch 32 - Val Loss: 37.349   

tensor([ 87, 100,  25,  25,  11,  67,  79,  62,  72,  79, 100,  62,  55,  89,
         87,  25, 101,  45,  58,   1,  20,  20,  11,   5,  11,   1,  39,  25])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 97%|█████████▋| 29/30 [23:15<00:48, 48.27s/it]

model train true


Thu 23:57:15,732 INF Training Started                                                                                                
Thu 23:57:18,181 INF Epoch 30 - Batch 1 - Train Loss: 4.057197093963623                                                              
Thu 23:57:19,042 INF Epoch 30 - Batch 2 - Train Loss: 3.8501994609832764                                                             
Thu 23:57:20,491 INF Epoch 30 - Batch 3 - Train Loss: 3.723632574081421                                                              
Thu 23:57:21,448 INF Epoch 30 - Batch 4 - Train Loss: 3.7575814723968506                                                             
Thu 23:57:22,353 INF Epoch 30 - Batch 5 - Train Loss: 3.7277305126190186                                                             
Thu 23:57:23,287 INF Epoch 30 - Batch 6 - Train Loss: 3.5366134643554688                                                             
Thu 23:57:24,139 INF Epoch 30 - Batch 7 - Train Loss: 3.946914

lr =  0.01
model train false


Thu 23:57:53,872 INF Epoch 30 - Batch 32 - Val Loss: 4.304                                                                           
Thu 23:57:54,309 INF Epoch 30 - Batch 32 - Val Loss: 8.840                                                                           
Thu 23:57:54,607 INF Epoch 30 - Batch 32 - Val Loss: 12.754                                                                          
Thu 23:57:54,952 INF Epoch 30 - Batch 32 - Val Loss: 16.859                                                                          
Thu 23:57:55,250 INF Epoch 30 - Batch 32 - Val Loss: 20.450                                                                          
Thu 23:57:55,545 INF Epoch 30 - Batch 32 - Val Loss: 24.450                                                                          
Thu 23:57:55,824 INF Epoch 30 - Batch 32 - Val Loss: 28.821                                                                          
Thu 23:57:56,134 INF Epoch 30 - Batch 32 - Val Loss: 33.108   

tensor([25, 60, 99, 99, 62, 99, 53, 62, 49, 25, 57, 54, 62, 60, 90, 60, 57, 99,
        57,  1, 73, 96, 62, 59, 62, 99, 57, 62])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


100%|██████████| 30/30 [24:03<00:00, 48.12s/it]


In [11]:
break here

SyntaxError: invalid syntax (<ipython-input-11-3ef470a3d0aa>, line 1)

In [ ]:
list(model_data.named_modules())

[('',
  MobileNetV3(
    (features): Sequential(
      (0): Conv2dNormActivation(
        (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): Hardswish()
      )
      (1): InvertedResidual(
        (block): Sequential(
          (0): Conv2dNormActivation(
            (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=16, bias=False)
            (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
            (2): ReLU(inplace=True)
          )
          (1): SqueezeExcitation(
            (avgpool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1))
            (fc2): Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1))
            (activation): ReLU()
            (scale_activation): Hardsigmoid()
          )
          (2): Conv2dNormActivation(


In [ ]:
print(model_data.avgpool)
print(model_data.classifier.in_features)

AdaptiveAvgPool2d(output_size=1)
576


In [ ]:
a =(model_data.avgpool)
print(a)
b = 'model_data.avgpool'
print(b)
print(b.split('.')[1])
c = eval(b)
print(c)


AdaptiveAvgPool2d(output_size=1)
model_data.avgpool
avgpool
AdaptiveAvgPool2d(output_size=1)
AdaptiveAvgPool2d(output_size=1)


In [ ]:
import tqdm
from pytorch_grad_cam import GradCAM
from mb_pytorch.utils.viewer import new_show_cam_on_image

model_data.to(device)

for i in tqdm.tqdm(range(20)):
        
        ##train loop
        
        model_data.train()
        train_loss = 0
        
        if logger:
            logger.info('Training Started')
        for j,(x,y) in enumerate(train_loader):
            x,y = x.to(device),y.to(device)
            optimizer.zero_grad()
            y_pred = model_data(x)
            current_loss = loss_attr()(y_pred,y)
            current_loss.backward()            
            optimizer.step()
            if scheduler is not None:
                scheduler.step()    
            train_loss += current_loss.item()
            if logger:
                logger.info(f'Epoch {i+1} - Batch {j+1} - Train Loss: {current_loss.item()}')
            
            #get grad cam images
            gradcam=['model_data.classifier']
            if gradcam and writer is not None:
                x_grad = x[0,:].to('cpu')
                x_grad = x_grad.unsqueeze(0)
                y_grad = y[0].to('cpu')
                for cam_layers in gradcam:
                    str_cam_layers = str(cam_layers)
                    print(str_cam_layers.split('.')[1])
                    grad_cam_layer= eval(cam_layers)
                    print(grad_cam_layer)
                    djkfals
                    
                    if logger:
                        logger.info(f'Gradcam for layer {cam_layers} started')
                    with GradCAM(model=model_data,target_layers=[cam_layers],use_cuda=False) as cm: 
                        try:
                            cr = cm(input_tensor=x_grad)[0,:]  
                        except:
                            cr = None 
                            if logger:
                                logger.info(f'Gradcam for layer {cam_layers} failed')
                        if cr is not None:
                            if logger:
                                logger.info(f'Gradcam for layer {cam_layers} completed')
                            cam_img = new_show_cam_on_image(x_grad[0].numpy(),cr,use_rgb=False)
                            writer.add_image(f'Gradcam/{cam_layers}',cam_img,global_step=i)
        avg_train_loss = train_loss / len(train_loader)
        if logger:
            logger.info(f'Epoch {i+1} - Train Loss: {avg_train_loss}')
    

  0%|          | 0/20 [00:00<?, ?it/s]Tue 13:37:04,193 INF Training Started                                                                                                
Tue 13:37:04,911 INF Epoch 1 - Batch 1 - Train Loss: 2.4315595626831055                                                              


classifier
Linear(in_features=576, out_features=10, bias=True)


  0%|          | 0/20 [00:00<?, ?it/s]


NameError: name 'djkfals' is not defined

In [ ]:
## old process

import tqdm
from torch.utils.tensorboard import SummaryWriter
import os


for i in tqdm.tqdm(range(all_model_data['model_epochs'])):
    ##train loop
    model_data.train()
    train_loss = 0
    for j,(x,y) in enumerate(train_loader10):
        x,y = x.to(device),y.to(device)
        optimizer.zero_grad()
        y_pred = model_data(x)
        current_loss = loss_attr()(y_pred,y)
        current_loss.backward()    
        optimizer.step()
        train_loss += current_loss.item()
        logger.info(f'Epoch {i+1} - Batch {j+1} - Train Loss: {current_loss.item()}')
    
    avg_train_loss = train_loss / len(train_loader)
    logger.info(f'Epoch {i+1} - Train Loss: {avg_train_loss}')
    
    writer.add_scalar('Loss/train', avg_train_loss, global_step=i)
        
    if scheduler is not None:
        scheduler.step()
    
    for name, param in model_data.named_parameters():
        writer.add_histogram(name, param, global_step=i)
        
    #get grad cam images
        
    #validation loop
    val_loss = 0
    val_acc = 0
    num_samples = 0
    
    model_data.eval()
    with torch.no_grad():
        for x_val, y_val in val_loader10:
            x_val, y_val = x_val.to(device), y_val.to(device)
            output = model_data(x_val)
            val_loss += loss_attr()(output, y_val).item() * x_val.size(0)
            _, preds = torch.max(output, 1)
            val_acc += torch.sum(preds == y_val.data)
            num_samples += x_val.size(0)
            logger.info(f'Epoch {i+1} - Batch {j+1} - Val Loss: {val_loss}')
        
        if num_samples == 0:
            num_samples = 1
        val_loss /= num_samples
        val_acc = val_acc / num_samples
        logger.info(f'Epoch {i+1} - Val Loss: {val_loss}', f'Epoch {i+1} - Val Acc: {val_acc}')
    
    writer.add_scalar('Loss/val', val_loss, global_step=i)
    writer.add_scalar('Accuracy/val', val_acc, global_step=i)
    
    # save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model = model_data.state_dict()

        path = os.path.join(all_data['data']['work_dir'], 'best_model.pth')
        torch.save(best_model, path)
        logger.info(f'Epoch {i+1} - Best Model Saved')
        
    model_data.train()
        


  0%|          | 0/50 [00:00<?, ?it/s]Tue 01:34:05,255 INF Epoch 1 - Batch 1 - Train Loss: 2.7716147899627686                                                              
Tue 01:34:07,058 INF Epoch 1 - Batch 2 - Train Loss: 3.0471785068511963                                                              
Tue 01:34:08,862 INF Epoch 1 - Batch 3 - Train Loss: 3.576723575592041                                                               
Tue 01:34:10,702 INF Epoch 1 - Batch 4 - Train Loss: 3.355401039123535                                                               
Tue 01:34:12,620 INF Epoch 1 - Batch 5 - Train Loss: 3.2821779251098633                                                              
Tue 01:34:14,500 INF Epoch 1 - Batch 6 - Train Loss: 3.361398220062256                                                               
Tue 01:34:16,429 INF Epoch 1 - Batch 7 - Train Loss: 3.22971510887146                                                                
Tue 01:34:18,368 INF Epo

In [ ]:
from mb_pytorch.utils.extra_utils import feature_view

for l in train_loader10:
    x,y = l
    break

from mb_pytorch.utils.extra_utils import get_model_summary
get_model_summary(model_data,input_size=(3,32,32))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 16, 16]           9,408
       BatchNorm2d-2           [-1, 64, 16, 16]             128
              ReLU-3           [-1, 64, 16, 16]               0
         MaxPool2d-4             [-1, 64, 8, 8]               0
            Conv2d-5             [-1, 64, 8, 8]           4,096
       BatchNorm2d-6             [-1, 64, 8, 8]             128
              ReLU-7             [-1, 64, 8, 8]               0
            Conv2d-8             [-1, 64, 8, 8]          36,864
       BatchNorm2d-9             [-1, 64, 8, 8]             128
             ReLU-10             [-1, 64, 8, 8]               0
           Conv2d-11            [-1, 256, 8, 8]          16,384
      BatchNorm2d-12            [-1, 256, 8, 8]             512
           Conv2d-13            [-1, 256, 8, 8]          16,384
      BatchNorm2d-14            [-1, 25

In [ ]:
list(model_data.named_modules()).index(('conv1', model_data.conv1))

1

In [ ]:
model_data.layer4[-1]

Bottleneck(
  (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
)

In [ ]:
list(model_data.named_modules()).index(('fc', model_data.fc))

150

In [ ]:
from mb_pytorch.models.modelloader import ModelLoader
from mb_pytorch.dataloader.loader import DataLoader
from mb_pytorch.training.train_params import train_helper
from torch.utils.tensorboard import SummaryWriter
import os
from mb_utils.src.logging import logger
import torch
from mb_pytorch.classification.training import classification_train_loop

k = DataLoader('/home/malav/jupyter_tests/Malav/classification.yaml')

k_data = k.data_dict['data']
model_data_dict = k.data_dict['model']

model_data_load = ModelLoader(k.data_dict['model'])
model_data =  model_data_load.get_model()
train_loader,val_loader,_,_ = k.data_load()
all_data = k.data_dict

model_yaml_data = k.data_dict['model']
loss_attr,optimizer_attr,optimizer_dict,scheduler_attr,scheduler_dict = train_helper(model_yaml_data)

optimizer =optimizer_attr(model_data.parameters(),**optimizer_dict)
scheduler = scheduler_attr(optimizer,**scheduler_dict)
best_val_loss = float('inf')
path_logs = os.path.join(all_data['data']['work_dir'], 'logs')
writer = SummaryWriter(log_dir=path_logs)
all_model_data= k.data_dict['model']

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

classification_train_loop(k_data,model_data_dict,model_data,train_loader,val_loader,loss_attr,optimizer,scheduler,writer,logger=logger,gradcam=['model_data.fc'],device=device)

