In [1]:
#function to test models 
import nest_asyncio
import warnings
from mb_utils.src.logging import logger

nest_asyncio.apply()
warnings.filterwarnings("ignore")


In [2]:
from mb_pytorch.models.modelloader import ModelLoader,ModelExtractor
from mb_pytorch.dataloader.loader import DataLoader

k = DataLoader('../scripts/model_load/loader_y.yaml',logger=logger)
k_data = k.data_dict['data']
model_data_dict = k.data_dict['model']

Fri 02:07:56,733 INF Read data from yaml file: [{'data': {'from_datasets': 'Flowers102', 'from_file': False, 'work_dir': '/home/malav
Fri 02:07:56,734 INF Data folder already exists. Using existing data folder :  /home/malav/mb_pytorch/data/                          


In [3]:
k.data_dict

{'data': {'from_datasets': 'Flowers102',
  'from_file': False,
  'work_dir': '/home/malav/mb_pytorch/data/',
  'file': '/home/malav/mb_pytorch/data/csv/file_data.csv',
  'use_img_dir': True,
  'img_dir': '/home/malav/mb_pytorch/data/images1/',
  'thresholding_pd': 0},
 'train_params': {'batch_size': 32,
  'num_workers': 4,
  'pin_memory': True,
  'shuffle': True,
  'seed': 42},
 'test_params': {'batch_size': 32,
  'num_workers': 4,
  'pin_memory': True,
  'shuffle': False,
  'seed': 42},
 'transforms_list': {'transform': True,
  'resize': {'val': True, 'args': {'size': [64, 64]}},
  'random_crop': {'val': False, 'args': {'size': [62, 62]}},
  'random_horizontal_flip': {'val': True, 'args': {'p': 0.5}},
  'random_vertical_flip': {'val': False, 'args': {'p': 0.5}},
  'random_rotation': {'val': False, 'args': {'degrees': 90}},
  'random_grayscale': {'val': False, 'args': {'p': 0.1}},
  'random_color_jitter': {'val': True,
   'args': {'brightness': 0.4,
    'contrast': 0.4,
    'saturation

In [4]:
model_data_load = ModelLoader(k.data_dict['model'])

model_data =  model_data_load.get_model()
model_data_ex = ModelExtractor(model_data)

train_loader,val_loader,_,_ = k.data_load()

all_data = k.data_dict

Fri 02:07:57,214 INF Model resnet18 loaded from torchvision.models.                                                                  
Fri 02:07:57,216 INF Data file: Flowers102 loading from torchvision.datasets.                                                        
Fri 02:07:57,229 INF Read data from yaml file: [{'data': {'from_datasets': 'Flowers102', 'from_file': False, 'work_dir': '/home/malav
Fri 02:07:57,231 INF transforms: [ToTensor(), Resize(size=[64, 64], interpolation=bilinear, max_size=None, antialias=warn), RandomHor
Fri 02:07:57,369 INF Read data from yaml file: [{'data': {'from_datasets': 'Flowers102', 'from_file': False, 'work_dir': '/home/malav
Fri 02:07:57,373 INF transforms: [ToTensor(), Resize(size=[64, 64], interpolation=bilinear, max_size=None, antialias=warn), RandomHor


In [5]:
from mb_pytorch.training.train_params import train_helper

model_yaml_data = k.data_dict['model']
loss_attr,optimizer_attr,optimizer_dict,scheduler_attr,scheduler_dict = train_helper(model_yaml_data) 

In [6]:
import torch.nn.functional as F
loss_attr = F.cross_entropy

In [7]:
print(loss_attr)
print(optimizer_attr)
print(optimizer_dict)
print(scheduler_attr)
print(scheduler_dict)

<function cross_entropy at 0x7efed938bdc0>
<class 'torch.optim.adam.Adam'>
{'lr': 0.01, 'betas': [0.9, 0.999], 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}
<class 'torch.optim.lr_scheduler.StepLR'>
{'step_size': 3, 'gamma': 0.2}


In [8]:

from torch.utils.tensorboard import SummaryWriter
import os
import torch
## setting the trianing params

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

optimizer = optimizer_attr(model_data.parameters(),**optimizer_dict)
scheduler = scheduler_attr(optimizer,**scheduler_dict)

best_val_loss = float('inf')

path_logs = os.path.join(all_data['data']['work_dir'], 'logs')
writer = SummaryWriter(log_dir=path_logs)

all_model_data= k.data_dict['model']


In [9]:
from mb_utils.src.logging import logger
from itertools import islice


train_loader10 = islice(train_loader, 10)
val_loader10 = islice(val_loader, 10)


In [10]:
model_data

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [11]:
from mb_pytorch.classification.training import classification_train_loop

classification_train_loop(k_data,model_data_dict,model_data,train_loader,val_loader,loss_attr,optimizer,scheduler=None,writer=writer,logger=logger,gradcam=['model_data.avgpool'],device=device)
####gradcam_layers=['model_data.features[-1][0]','model_data.features[0][0]']

  0%|          | 0/30 [00:00<?, ?it/s]Fri 02:08:51,260 INF Training Started                                                                                                
Fri 02:08:52,383 INF Epoch 1 - Batch 1 - Train Loss: 4.798352241516113                                                               
Fri 02:08:52,601 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:08:53,010 INF Epoch 1 - Batch 2 - Train Loss: 47939.41015625                                                                  
Fri 02:08:53,931 INF Epoch 1 - Batch 3 - Train Loss: 56.6110954284668                                                                
Fri 02:08:54,370 INF Epoch 1 - Batch 4 - Train Loss: 155.09942626953125                                                              
Fri 02:08:54,791 INF Epoch 1 - Batch 5 - Train Loss: 10.075271606445312                                                              
Fri 02:08:55,215 INF Epo

lr =  0.01


Fri 02:09:09,000 INF Epoch 1 - Batch 32 - Val Loss: 4.608                                                                            
Fri 02:09:09,136 INF Epoch 1 - Batch 32 - Val Loss: 9.229                                                                            
Fri 02:09:09,246 INF Epoch 1 - Batch 32 - Val Loss: 13.870                                                                           
Fri 02:09:09,361 INF Epoch 1 - Batch 32 - Val Loss: 18.508                                                                           
Fri 02:09:09,512 INF Epoch 1 - Batch 32 - Val Loss: 23.119                                                                           
Fri 02:09:09,632 INF Epoch 1 - Batch 32 - Val Loss: 27.691                                                                           
Fri 02:09:09,745 INF Epoch 1 - Batch 32 - Val Loss: 32.329                                                                           
Fri 02:09:09,861 INF Epoch 1 - Batch 32 - Val Loss: 36.957    

tensor([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:09:13,823 INF Epoch 1 - Best Model Saved                                                                                      
  3%|▎         | 1/30 [00:22<10:54, 22.57s/it]Fri 02:09:13,835 INF Training Started                                                                                                
Fri 02:09:15,034 INF Epoch 2 - Batch 1 - Train Loss: 19.157190322875977                                                              
Fri 02:09:15,079 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:09:15,527 INF Epoch 2 - Batch 2 - Train Loss: 6.355204105377197                                                               
Fri 02:09:16,292 INF Epoch 2 - Batch 3 - Train Loss: 4.831785202026367                                                               
Fri 02:09:16,747 INF Epoch 2 - Batch 4 - Train Loss: 4.609830379486084                                                               
Fri 02:09:17,211

lr =  0.01


Fri 02:09:32,026 INF Epoch 2 - Batch 32 - Val Loss: 4.587                                                                            
Fri 02:09:32,164 INF Epoch 2 - Batch 32 - Val Loss: 9.213                                                                            
Fri 02:09:32,287 INF Epoch 2 - Batch 32 - Val Loss: 13.840                                                                           
Fri 02:09:32,409 INF Epoch 2 - Batch 32 - Val Loss: 18.486                                                                           
Fri 02:09:32,568 INF Epoch 2 - Batch 32 - Val Loss: 23.113                                                                           
Fri 02:09:32,686 INF Epoch 2 - Batch 32 - Val Loss: 27.715                                                                           
Fri 02:09:32,808 INF Epoch 2 - Batch 32 - Val Loss: 32.350                                                                           
Fri 02:09:32,948 INF Epoch 2 - Batch 32 - Val Loss: 36.964    

tensor([37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:09:37,134 INF Epoch 2 - Best Model Saved                                                                                      
  7%|▋         | 2/30 [00:45<10:44, 23.01s/it]Fri 02:09:37,146 INF Training Started                                                                                                
Fri 02:09:38,495 INF Epoch 3 - Batch 1 - Train Loss: 24.736251831054688                                                              
Fri 02:09:38,552 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:09:39,039 INF Epoch 3 - Batch 2 - Train Loss: 4.631656169891357                                                               
Fri 02:09:39,856 INF Epoch 3 - Batch 3 - Train Loss: 4.619738578796387                                                               
Fri 02:09:40,342 INF Epoch 3 - Batch 4 - Train Loss: 4.601490497589111                                                               
Fri 02:09:40,830

lr =  0.01


Fri 02:09:56,825 INF Epoch 3 - Batch 32 - Val Loss: 4.606                                                                            
Fri 02:09:56,969 INF Epoch 3 - Batch 32 - Val Loss: 9.218                                                                            
Fri 02:09:57,115 INF Epoch 3 - Batch 32 - Val Loss: 13.867                                                                           
Fri 02:09:57,259 INF Epoch 3 - Batch 32 - Val Loss: 18.515                                                                           
Fri 02:09:57,428 INF Epoch 3 - Batch 32 - Val Loss: 23.165                                                                           
Fri 02:09:57,572 INF Epoch 3 - Batch 32 - Val Loss: 27.797                                                                           
Fri 02:09:57,714 INF Epoch 3 - Batch 32 - Val Loss: 32.473                                                                           
Fri 02:09:57,847 INF Epoch 3 - Batch 32 - Val Loss: 37.061    

tensor([23, 27, 27, 64, 27, 27, 64, 64, 64, 23, 64, 23, 64, 64, 64, 27, 64, 64,
        27, 64, 27, 64, 27, 64, 27, 23, 64, 27])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 10%|█         | 3/30 [01:10<10:40, 23.74s/it]Fri 02:10:01,785 INF Training Started                                                                                                
Fri 02:10:03,069 INF Epoch 4 - Batch 1 - Train Loss: 20.44658088684082                                                               
Fri 02:10:03,120 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:10:03,617 INF Epoch 4 - Batch 2 - Train Loss: 4.703056335449219                                                               
Fri 02:10:04,476 INF Epoch 4 - Batch 3 - Train Loss: 4.6278276443481445                                                              
Fri 02:10:05,008 INF Epoch 4 - Batch 4 - Train Loss: 4.62099552154541                                                                
Fri 02:10:05,541 INF Epoch 4 - Batch 5 - Train Loss: 4.653278827667236                                                               
Fri 02:10:06,059

lr =  0.01


Fri 02:10:21,557 INF Epoch 4 - Batch 32 - Val Loss: 4.601                                                                            
Fri 02:10:21,708 INF Epoch 4 - Batch 32 - Val Loss: 9.213                                                                            
Fri 02:10:21,848 INF Epoch 4 - Batch 32 - Val Loss: 13.857                                                                           
Fri 02:10:21,989 INF Epoch 4 - Batch 32 - Val Loss: 18.506                                                                           
Fri 02:10:22,159 INF Epoch 4 - Batch 32 - Val Loss: 23.141                                                                           
Fri 02:10:22,294 INF Epoch 4 - Batch 32 - Val Loss: 27.765                                                                           
Fri 02:10:22,419 INF Epoch 4 - Batch 32 - Val Loss: 32.392                                                                           
Fri 02:10:22,550 INF Epoch 4 - Batch 32 - Val Loss: 36.999    

tensor([64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64, 64, 64, 64, 64, 64, 64])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 13%|█▎        | 4/30 [01:35<10:26, 24.09s/it]Fri 02:10:26,434 INF Training Started                                                                                                
Fri 02:10:27,775 INF Epoch 5 - Batch 1 - Train Loss: 13.417242050170898                                                              
Fri 02:10:27,833 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:10:28,337 INF Epoch 5 - Batch 2 - Train Loss: 4.645496368408203                                                               
Fri 02:10:29,166 INF Epoch 5 - Batch 3 - Train Loss: 4.627744197845459                                                               
Fri 02:10:29,686 INF Epoch 5 - Batch 4 - Train Loss: 4.634061336517334                                                               
Fri 02:10:30,183 INF Epoch 5 - Batch 5 - Train Loss: 4.630162239074707                                                               
Fri 02:10:30,676

lr =  0.01


Fri 02:10:46,231 INF Epoch 5 - Batch 32 - Val Loss: 4.601                                                                            
Fri 02:10:46,367 INF Epoch 5 - Batch 32 - Val Loss: 9.209                                                                            
Fri 02:10:46,498 INF Epoch 5 - Batch 32 - Val Loss: 13.856                                                                           
Fri 02:10:46,634 INF Epoch 5 - Batch 32 - Val Loss: 18.508                                                                           
Fri 02:10:46,826 INF Epoch 5 - Batch 32 - Val Loss: 23.135                                                                           
Fri 02:10:46,970 INF Epoch 5 - Batch 32 - Val Loss: 27.731                                                                           
Fri 02:10:47,137 INF Epoch 5 - Batch 32 - Val Loss: 32.388                                                                           
Fri 02:10:47,271 INF Epoch 5 - Batch 32 - Val Loss: 36.973    

tensor([94, 94, 94, 94, 94, 94, 56, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
        94, 94, 94, 94, 94, 94, 94, 94, 94, 94])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 17%|█▋        | 5/30 [01:59<10:09, 24.36s/it]Fri 02:10:51,247 INF Training Started                                                                                                
Fri 02:10:52,711 INF Epoch 6 - Batch 1 - Train Loss: 10.46246337890625                                                               
Fri 02:10:52,762 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:10:53,247 INF Epoch 6 - Batch 2 - Train Loss: 4.636529922485352                                                               
Fri 02:10:54,120 INF Epoch 6 - Batch 3 - Train Loss: 4.621389389038086                                                               
Fri 02:10:54,624 INF Epoch 6 - Batch 4 - Train Loss: 4.677398204803467                                                               
Fri 02:10:55,147 INF Epoch 6 - Batch 5 - Train Loss: 4.611982345581055                                                               
Fri 02:10:55,630

lr =  0.01


Fri 02:11:11,112 INF Epoch 6 - Batch 32 - Val Loss: 4.595                                                                            
Fri 02:11:11,244 INF Epoch 6 - Batch 32 - Val Loss: 9.207                                                                            
Fri 02:11:11,389 INF Epoch 6 - Batch 32 - Val Loss: 13.839                                                                           
Fri 02:11:11,520 INF Epoch 6 - Batch 32 - Val Loss: 18.486                                                                           
Fri 02:11:11,692 INF Epoch 6 - Batch 32 - Val Loss: 23.108                                                                           
Fri 02:11:11,827 INF Epoch 6 - Batch 32 - Val Loss: 27.724                                                                           
Fri 02:11:11,965 INF Epoch 6 - Batch 32 - Val Loss: 32.352                                                                           
Fri 02:11:12,125 INF Epoch 6 - Batch 32 - Val Loss: 36.958    

tensor([26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 20%|██        | 6/30 [02:24<09:48, 24.53s/it]Fri 02:11:16,132 INF Training Started                                                                                                
Fri 02:11:17,535 INF Epoch 7 - Batch 1 - Train Loss: 11.849626541137695                                                              
Fri 02:11:17,588 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:11:18,086 INF Epoch 7 - Batch 2 - Train Loss: 4.609228134155273                                                               
Fri 02:11:18,991 INF Epoch 7 - Batch 3 - Train Loss: 4.596042633056641                                                               
Fri 02:11:19,482 INF Epoch 7 - Batch 4 - Train Loss: 4.625297546386719                                                               
Fri 02:11:19,993 INF Epoch 7 - Batch 5 - Train Loss: 4.630126953125                                                                  
Fri 02:11:20,476

lr =  0.01


Fri 02:11:36,370 INF Epoch 7 - Batch 32 - Val Loss: 4.631                                                                            
Fri 02:11:36,507 INF Epoch 7 - Batch 32 - Val Loss: 9.246                                                                            
Fri 02:11:36,652 INF Epoch 7 - Batch 32 - Val Loss: 13.874                                                                           
Fri 02:11:36,790 INF Epoch 7 - Batch 32 - Val Loss: 18.537                                                                           
Fri 02:11:36,951 INF Epoch 7 - Batch 32 - Val Loss: 23.161                                                                           
Fri 02:11:37,085 INF Epoch 7 - Batch 32 - Val Loss: 27.769                                                                           
Fri 02:11:37,208 INF Epoch 7 - Batch 32 - Val Loss: 32.398                                                                           
Fri 02:11:37,343 INF Epoch 7 - Batch 32 - Val Loss: 36.976    

tensor([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
        101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:11:41,894 INF Epoch 7 - Best Model Saved                                                                                      
 23%|██▎       | 7/30 [02:50<09:33, 24.95s/it]Fri 02:11:41,907 INF Training Started                                                                                                
Fri 02:11:43,260 INF Epoch 8 - Batch 1 - Train Loss: 6.190428733825684                                                               
Fri 02:11:43,309 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:11:43,880 INF Epoch 8 - Batch 2 - Train Loss: 4.609261989593506                                                               
Fri 02:11:44,785 INF Epoch 8 - Batch 3 - Train Loss: 4.613873481750488                                                               
Fri 02:11:45,279 INF Epoch 8 - Batch 4 - Train Loss: 4.648777961730957                                                               
Fri 02:11:45,771

lr =  0.01


Fri 02:12:02,697 INF Epoch 8 - Batch 32 - Val Loss: 4.668                                                                            
Fri 02:12:02,831 INF Epoch 8 - Batch 32 - Val Loss: 9.276                                                                            
Fri 02:12:02,958 INF Epoch 8 - Batch 32 - Val Loss: 13.889                                                                           
Fri 02:12:03,084 INF Epoch 8 - Batch 32 - Val Loss: 18.532                                                                           
Fri 02:12:03,253 INF Epoch 8 - Batch 32 - Val Loss: 23.154                                                                           
Fri 02:12:03,385 INF Epoch 8 - Batch 32 - Val Loss: 27.751                                                                           
Fri 02:12:03,528 INF Epoch 8 - Batch 32 - Val Loss: 32.365                                                                           
Fri 02:12:03,670 INF Epoch 8 - Batch 32 - Val Loss: 36.969    

tensor([26, 38, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 27%|██▋       | 8/30 [03:16<09:15, 25.24s/it]Fri 02:12:07,807 INF Training Started                                                                                                
Fri 02:12:09,191 INF Epoch 9 - Batch 1 - Train Loss: 5.333488464355469                                                               
Fri 02:12:09,248 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:12:09,776 INF Epoch 9 - Batch 2 - Train Loss: 4.699769973754883                                                               
Fri 02:12:10,640 INF Epoch 9 - Batch 3 - Train Loss: 4.623847484588623                                                               
Fri 02:12:11,107 INF Epoch 9 - Batch 4 - Train Loss: 4.656558990478516                                                               
Fri 02:12:11,611 INF Epoch 9 - Batch 5 - Train Loss: 4.629514694213867                                                               
Fri 02:12:12,114

lr =  0.01


Fri 02:12:28,293 INF Epoch 9 - Batch 32 - Val Loss: 4.634                                                                            
Fri 02:12:28,433 INF Epoch 9 - Batch 32 - Val Loss: 9.245                                                                            
Fri 02:12:28,580 INF Epoch 9 - Batch 32 - Val Loss: 13.859                                                                           
Fri 02:12:28,719 INF Epoch 9 - Batch 32 - Val Loss: 18.484                                                                           
Fri 02:12:28,884 INF Epoch 9 - Batch 32 - Val Loss: 23.127                                                                           
Fri 02:12:29,032 INF Epoch 9 - Batch 32 - Val Loss: 27.738                                                                           
Fri 02:12:29,172 INF Epoch 9 - Batch 32 - Val Loss: 32.380                                                                           
Fri 02:12:29,309 INF Epoch 9 - Batch 32 - Val Loss: 37.007    

tensor([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
        33, 33, 33, 33, 33, 33, 33, 33, 33, 33])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 30%|███       | 9/30 [03:42<08:53, 25.39s/it]Fri 02:12:33,517 INF Training Started                                                                                                
Fri 02:12:34,873 INF Epoch 10 - Batch 1 - Train Loss: 5.297360420227051                                                              
Fri 02:12:34,925 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:12:35,464 INF Epoch 10 - Batch 2 - Train Loss: 4.626674652099609                                                              
Fri 02:12:36,419 INF Epoch 10 - Batch 3 - Train Loss: 4.621950149536133                                                              
Fri 02:12:36,982 INF Epoch 10 - Batch 4 - Train Loss: 4.639386177062988                                                              
Fri 02:12:37,467 INF Epoch 10 - Batch 5 - Train Loss: 4.626915454864502                                                              
Fri 02:12:37,977

lr =  0.01


Fri 02:12:54,191 INF Epoch 10 - Batch 32 - Val Loss: 4.639                                                                           
Fri 02:12:54,348 INF Epoch 10 - Batch 32 - Val Loss: 9.250                                                                           
Fri 02:12:54,505 INF Epoch 10 - Batch 32 - Val Loss: 13.885                                                                          
Fri 02:12:54,653 INF Epoch 10 - Batch 32 - Val Loss: 18.519                                                                          
Fri 02:12:54,808 INF Epoch 10 - Batch 32 - Val Loss: 23.141                                                                          
Fri 02:12:54,972 INF Epoch 10 - Batch 32 - Val Loss: 27.751                                                                          
Fri 02:12:55,116 INF Epoch 10 - Batch 32 - Val Loss: 32.360                                                                          
Fri 02:12:55,261 INF Epoch 10 - Batch 32 - Val Loss: 36.988   

tensor([62, 62, 57, 62, 62, 62, 62, 62, 62, 62, 57, 62, 62, 62, 62, 62, 62, 62,
        62, 57, 62, 62, 62, 62, 62, 62, 62, 62])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:13:00,003 INF Epoch 10 - Best Model Saved                                                                                     
 33%|███▎      | 10/30 [04:08<08:34, 25.74s/it]Fri 02:13:00,013 INF Training Started                                                                                                
Fri 02:13:01,521 INF Epoch 11 - Batch 1 - Train Loss: 4.898956775665283                                                              
Fri 02:13:01,577 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:13:02,159 INF Epoch 11 - Batch 2 - Train Loss: 4.619662761688232                                                              
Fri 02:13:03,025 INF Epoch 11 - Batch 3 - Train Loss: 4.620944023132324                                                              
Fri 02:13:03,539 INF Epoch 11 - Batch 4 - Train Loss: 4.6331915855407715                                                             
Fri 02:13:04,06

lr =  0.01


Fri 02:13:20,974 INF Epoch 11 - Batch 32 - Val Loss: 4.602                                                                           
Fri 02:13:21,127 INF Epoch 11 - Batch 32 - Val Loss: 9.243                                                                           
Fri 02:13:21,280 INF Epoch 11 - Batch 32 - Val Loss: 14.091                                                                          
Fri 02:13:21,427 INF Epoch 11 - Batch 32 - Val Loss: 18.792                                                                          
Fri 02:13:21,593 INF Epoch 11 - Batch 32 - Val Loss: 23.296                                                                          
Fri 02:13:21,734 INF Epoch 11 - Batch 32 - Val Loss: 27.909                                                                          
Fri 02:13:21,893 INF Epoch 11 - Batch 32 - Val Loss: 32.561                                                                          
Fri 02:13:22,065 INF Epoch 11 - Batch 32 - Val Loss: 37.120   

tensor([14, 14, 62, 14, 14, 33, 33, 33, 14, 79, 14, 79, 62, 33, 79, 33, 33, 33,
        33, 33, 14, 14, 33, 14, 33, 14, 33, 62])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 37%|███▋      | 11/30 [04:35<08:12, 25.93s/it]Fri 02:13:26,417 INF Training Started                                                                                                
Fri 02:13:27,825 INF Epoch 12 - Batch 1 - Train Loss: 4.86719274520874                                                               
Fri 02:13:27,880 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:13:28,414 INF Epoch 12 - Batch 2 - Train Loss: 4.684980392456055                                                              
Fri 02:13:29,379 INF Epoch 12 - Batch 3 - Train Loss: 4.597840785980225                                                              
Fri 02:13:29,895 INF Epoch 12 - Batch 4 - Train Loss: 4.632776260375977                                                              
Fri 02:13:30,451 INF Epoch 12 - Batch 5 - Train Loss: 4.60488748550415                                                               
Fri 02:13:30,97

lr =  0.01


Fri 02:13:48,560 INF Epoch 12 - Batch 32 - Val Loss: 4.633                                                                           
Fri 02:13:48,711 INF Epoch 12 - Batch 32 - Val Loss: 9.255                                                                           
Fri 02:13:48,872 INF Epoch 12 - Batch 32 - Val Loss: 13.950                                                                          
Fri 02:13:49,018 INF Epoch 12 - Batch 32 - Val Loss: 18.556                                                                          
Fri 02:13:49,184 INF Epoch 12 - Batch 32 - Val Loss: 23.111                                                                          
Fri 02:13:49,332 INF Epoch 12 - Batch 32 - Val Loss: 27.707                                                                          
Fri 02:13:49,479 INF Epoch 12 - Batch 32 - Val Loss: 32.345                                                                          
Fri 02:13:49,623 INF Epoch 12 - Batch 32 - Val Loss: 36.960   

tensor([39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
        39, 57, 39, 39, 39, 39, 39, 39, 39, 39])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:13:54,495 INF Epoch 12 - Best Model Saved                                                                                     
 40%|████      | 12/30 [05:03<07:58, 26.60s/it]Fri 02:13:54,504 INF Training Started                                                                                                
Fri 02:13:55,897 INF Epoch 13 - Batch 1 - Train Loss: 4.637129306793213                                                              
Fri 02:13:55,963 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:13:56,543 INF Epoch 13 - Batch 2 - Train Loss: 4.6146559715271                                                                
Fri 02:13:57,444 INF Epoch 13 - Batch 3 - Train Loss: 4.608950138092041                                                              
Fri 02:13:57,974 INF Epoch 13 - Batch 4 - Train Loss: 4.576752662658691                                                              
Fri 02:13:58,51

lr =  0.01


Fri 02:14:15,844 INF Epoch 13 - Batch 32 - Val Loss: 4.566                                                                           
Fri 02:14:16,011 INF Epoch 13 - Batch 32 - Val Loss: 9.252                                                                           
Fri 02:14:16,168 INF Epoch 13 - Batch 32 - Val Loss: 14.078                                                                          
Fri 02:14:16,331 INF Epoch 13 - Batch 32 - Val Loss: 18.735                                                                          
Fri 02:14:16,492 INF Epoch 13 - Batch 32 - Val Loss: 23.259                                                                          
Fri 02:14:16,645 INF Epoch 13 - Batch 32 - Val Loss: 27.852                                                                          
Fri 02:14:16,811 INF Epoch 13 - Batch 32 - Val Loss: 32.464                                                                          
Fri 02:14:16,971 INF Epoch 13 - Batch 32 - Val Loss: 37.060   

tensor([38, 59, 28, 59, 38, 28, 28, 28, 59, 38, 28, 28, 64, 28, 28, 28, 28, 28,
        26, 64, 26, 72, 28, 59, 28, 28, 59, 28])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:14:21,646 INF Epoch 13 - Best Model Saved                                                                                     
 43%|████▎     | 13/30 [05:30<07:35, 26.77s/it]Fri 02:14:21,658 INF Training Started                                                                                                
Fri 02:14:23,111 INF Epoch 14 - Batch 1 - Train Loss: 4.950060844421387                                                              
Fri 02:14:23,164 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:14:23,716 INF Epoch 14 - Batch 2 - Train Loss: 4.595839023590088                                                              
Fri 02:14:24,592 INF Epoch 14 - Batch 3 - Train Loss: 4.60341739654541                                                               
Fri 02:14:25,107 INF Epoch 14 - Batch 4 - Train Loss: 4.568709850311279                                                              
Fri 02:14:25,64

lr =  0.01


Fri 02:14:43,133 INF Epoch 14 - Batch 32 - Val Loss: 4.630                                                                           
Fri 02:14:43,305 INF Epoch 14 - Batch 32 - Val Loss: 9.222                                                                           
Fri 02:14:43,473 INF Epoch 14 - Batch 32 - Val Loss: 13.805                                                                          
Fri 02:14:43,624 INF Epoch 14 - Batch 32 - Val Loss: 18.418                                                                          
Fri 02:14:43,804 INF Epoch 14 - Batch 32 - Val Loss: 23.082                                                                          
Fri 02:14:43,951 INF Epoch 14 - Batch 32 - Val Loss: 27.707                                                                          
Fri 02:14:44,116 INF Epoch 14 - Batch 32 - Val Loss: 32.351                                                                          
Fri 02:14:44,271 INF Epoch 14 - Batch 32 - Val Loss: 36.967   

tensor([39, 39, 39, 39, 39, 60, 60, 60, 39, 39, 39, 39, 39, 39, 39, 39, 39, 60,
        39, 39, 39, 39, 39, 39, 39, 60, 39, 60])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 47%|████▋     | 14/30 [05:57<07:09, 26.86s/it]Fri 02:14:48,734 INF Training Started                                                                                                
Fri 02:14:50,254 INF Epoch 15 - Batch 1 - Train Loss: 4.667316436767578                                                              
Fri 02:14:50,308 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:14:50,846 INF Epoch 15 - Batch 2 - Train Loss: 4.623321533203125                                                              
Fri 02:14:51,759 INF Epoch 15 - Batch 3 - Train Loss: 4.614445209503174                                                              
Fri 02:14:52,303 INF Epoch 15 - Batch 4 - Train Loss: 4.648742198944092                                                              
Fri 02:14:52,863 INF Epoch 15 - Batch 5 - Train Loss: 4.618767738342285                                                              
Fri 02:14:53,40

lr =  0.01


Fri 02:15:10,298 INF Epoch 15 - Batch 32 - Val Loss: 4.609                                                                           
Fri 02:15:10,451 INF Epoch 15 - Batch 32 - Val Loss: 9.198                                                                           
Fri 02:15:10,616 INF Epoch 15 - Batch 32 - Val Loss: 13.839                                                                          
Fri 02:15:10,769 INF Epoch 15 - Batch 32 - Val Loss: 18.490                                                                          
Fri 02:15:10,942 INF Epoch 15 - Batch 32 - Val Loss: 22.872                                                                          
Fri 02:15:11,099 INF Epoch 15 - Batch 32 - Val Loss: 27.419                                                                          
Fri 02:15:11,249 INF Epoch 15 - Batch 32 - Val Loss: 32.050                                                                          
Fri 02:15:11,411 INF Epoch 15 - Batch 32 - Val Loss: 36.653   

tensor([82, 58,  8, 82,  8, 88, 88, 88, 82, 88, 58, 88, 88,  8, 88, 88,  8, 88,
        64, 67, 14, 64,  8, 82, 88,  8, 88, 88])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:15:16,148 INF Epoch 15 - Best Model Saved                                                                                     
 50%|█████     | 15/30 [06:24<06:45, 27.03s/it]Fri 02:15:16,159 INF Training Started                                                                                                
Fri 02:15:17,496 INF Epoch 16 - Batch 1 - Train Loss: 4.725982666015625                                                              
Fri 02:15:17,552 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:15:18,132 INF Epoch 16 - Batch 2 - Train Loss: 4.555681228637695                                                              
Fri 02:15:19,067 INF Epoch 16 - Batch 3 - Train Loss: 4.5717267990112305                                                             
Fri 02:15:19,559 INF Epoch 16 - Batch 4 - Train Loss: 4.584303855895996                                                              
Fri 02:15:20,08

lr =  0.01


Fri 02:15:36,844 INF Epoch 16 - Batch 32 - Val Loss: 4.611                                                                           
Fri 02:15:36,974 INF Epoch 16 - Batch 32 - Val Loss: 9.275                                                                           
Fri 02:15:37,105 INF Epoch 16 - Batch 32 - Val Loss: 13.827                                                                          
Fri 02:15:37,235 INF Epoch 16 - Batch 32 - Val Loss: 18.444                                                                          
Fri 02:15:37,556 INF Epoch 16 - Batch 32 - Val Loss: 22.777                                                                          
Fri 02:15:37,737 INF Epoch 16 - Batch 32 - Val Loss: 27.373                                                                          
Fri 02:15:37,889 INF Epoch 16 - Batch 32 - Val Loss: 31.987                                                                          
Fri 02:15:38,037 INF Epoch 16 - Batch 32 - Val Loss: 36.531   

tensor([14, 59, 59, 14, 88, 88, 88, 88, 14, 88, 14, 14, 88, 88, 88, 88, 88, 88,
        14, 59, 88, 88, 88, 59, 88, 88, 14, 88])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:15:42,556 INF Epoch 16 - Best Model Saved                                                                                     
 53%|█████▎    | 16/30 [06:51<06:15, 26.84s/it]Fri 02:15:42,569 INF Training Started                                                                                                
Fri 02:15:44,019 INF Epoch 17 - Batch 1 - Train Loss: 4.585771083831787                                                              
Fri 02:15:44,071 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:15:44,638 INF Epoch 17 - Batch 2 - Train Loss: 4.527419567108154                                                              
Fri 02:15:45,542 INF Epoch 17 - Batch 3 - Train Loss: 4.583568572998047                                                              
Fri 02:15:46,096 INF Epoch 17 - Batch 4 - Train Loss: 4.56398868560791                                                               
Fri 02:15:46,59

lr =  0.01


Fri 02:16:03,503 INF Epoch 17 - Batch 32 - Val Loss: 4.626                                                                           
Fri 02:16:03,662 INF Epoch 17 - Batch 32 - Val Loss: 9.284                                                                           
Fri 02:16:03,804 INF Epoch 17 - Batch 32 - Val Loss: 14.260                                                                          
Fri 02:16:03,949 INF Epoch 17 - Batch 32 - Val Loss: 18.882                                                                          
Fri 02:16:04,124 INF Epoch 17 - Batch 32 - Val Loss: 23.197                                                                          
Fri 02:16:04,267 INF Epoch 17 - Batch 32 - Val Loss: 27.783                                                                          
Fri 02:16:04,421 INF Epoch 17 - Batch 32 - Val Loss: 32.430                                                                          
Fri 02:16:04,562 INF Epoch 17 - Batch 32 - Val Loss: 36.973   

tensor([28, 57, 88, 95, 88, 88, 88, 88, 95, 28, 28, 57, 88, 88, 88, 95, 88, 88,
        95, 95, 59, 57, 88, 57, 88, 28, 57, 88])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 57%|█████▋    | 17/30 [07:17<05:46, 26.65s/it]Fri 02:16:08,806 INF Training Started                                                                                                
Fri 02:16:10,254 INF Epoch 18 - Batch 1 - Train Loss: 4.842035293579102                                                              
Fri 02:16:10,308 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:16:10,845 INF Epoch 18 - Batch 2 - Train Loss: 4.522268295288086                                                              
Fri 02:16:11,740 INF Epoch 18 - Batch 3 - Train Loss: 4.5181474685668945                                                             
Fri 02:16:12,308 INF Epoch 18 - Batch 4 - Train Loss: 4.649967670440674                                                              
Fri 02:16:12,836 INF Epoch 18 - Batch 5 - Train Loss: 4.55800724029541                                                               
Fri 02:16:13,38

lr =  0.01


Fri 02:16:30,308 INF Epoch 18 - Batch 32 - Val Loss: 4.611                                                                           
Fri 02:16:30,447 INF Epoch 18 - Batch 32 - Val Loss: 9.146                                                                           
Fri 02:16:30,607 INF Epoch 18 - Batch 32 - Val Loss: 13.723                                                                          
Fri 02:16:30,754 INF Epoch 18 - Batch 32 - Val Loss: 18.338                                                                          
Fri 02:16:30,915 INF Epoch 18 - Batch 32 - Val Loss: 22.948                                                                          
Fri 02:16:31,090 INF Epoch 18 - Batch 32 - Val Loss: 27.559                                                                          
Fri 02:16:31,243 INF Epoch 18 - Batch 32 - Val Loss: 32.214                                                                          
Fri 02:16:31,385 INF Epoch 18 - Batch 32 - Val Loss: 36.682   

tensor([ 8, 95, 79, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88,
        88, 88, 29,  8, 67, 57, 88, 88, 29, 88])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


 60%|██████    | 18/30 [07:44<05:20, 26.74s/it]Fri 02:16:35,751 INF Training Started                                                                                                
Fri 02:16:37,321 INF Epoch 19 - Batch 1 - Train Loss: 4.584135055541992                                                              
Fri 02:16:37,374 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:16:37,897 INF Epoch 19 - Batch 2 - Train Loss: 4.442922115325928                                                              
Fri 02:16:38,873 INF Epoch 19 - Batch 3 - Train Loss: 4.548831462860107                                                              
Fri 02:16:39,390 INF Epoch 19 - Batch 4 - Train Loss: 4.583281517028809                                                              
Fri 02:16:39,945 INF Epoch 19 - Batch 5 - Train Loss: 4.532171726226807                                                              
Fri 02:16:40,49

lr =  0.01


Fri 02:16:57,670 INF Epoch 19 - Batch 32 - Val Loss: 4.492                                                                           
Fri 02:16:57,811 INF Epoch 19 - Batch 32 - Val Loss: 9.071                                                                           
Fri 02:16:57,960 INF Epoch 19 - Batch 32 - Val Loss: 13.789                                                                          
Fri 02:16:58,155 INF Epoch 19 - Batch 32 - Val Loss: 18.404                                                                          
Fri 02:16:58,309 INF Epoch 19 - Batch 32 - Val Loss: 22.807                                                                          
Fri 02:16:58,462 INF Epoch 19 - Batch 32 - Val Loss: 27.445                                                                          
Fri 02:16:58,610 INF Epoch 19 - Batch 32 - Val Loss: 32.027                                                                          
Fri 02:16:58,769 INF Epoch 19 - Batch 32 - Val Loss: 36.556   

tensor([53, 15,  8, 28, 46, 90, 90, 67, 33,  8, 67, 33, 33, 90,  8, 67,  8, 67,
         8, 67, 46, 58, 90, 46, 67, 67, 67, 67])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:17:03,664 INF Epoch 19 - Best Model Saved                                                                                     
 63%|██████▎   | 19/30 [08:12<04:58, 27.10s/it]Fri 02:17:03,669 INF Training Started                                                                                                
Fri 02:17:05,160 INF Epoch 20 - Batch 1 - Train Loss: 4.538013935089111                                                              
Fri 02:17:05,219 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:17:05,740 INF Epoch 20 - Batch 2 - Train Loss: 4.55449104309082                                                               
Fri 02:17:06,652 INF Epoch 20 - Batch 3 - Train Loss: 4.58258056640625                                                               
Fri 02:17:07,175 INF Epoch 20 - Batch 4 - Train Loss: 4.5787034034729                                                                
Fri 02:17:07,63

lr =  0.01


Fri 02:17:21,571 INF Epoch 20 - Batch 32 - Val Loss: 4.523                                                                           
Fri 02:17:21,702 INF Epoch 20 - Batch 32 - Val Loss: 9.080                                                                           
Fri 02:17:21,887 INF Epoch 20 - Batch 32 - Val Loss: 13.712                                                                          
Fri 02:17:22,001 INF Epoch 20 - Batch 32 - Val Loss: 18.308                                                                          
Fri 02:17:22,115 INF Epoch 20 - Batch 32 - Val Loss: 22.777                                                                          
Fri 02:17:22,224 INF Epoch 20 - Batch 32 - Val Loss: 27.438                                                                          
Fri 02:17:22,337 INF Epoch 20 - Batch 32 - Val Loss: 32.042                                                                          
Fri 02:17:22,445 INF Epoch 20 - Batch 32 - Val Loss: 36.456   

tensor([ 24,  59,  24, 101,  67,  67,  24,  24,   8,   8,  53,  46,  39,   8,
         67,   8,   8,   8,  95,  67,  59,   8,  67,  57,  24,   8,  24,  67])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:17:26,495 INF Epoch 20 - Best Model Saved                                                                                     
 67%|██████▋   | 20/30 [08:35<04:18, 25.85s/it]Fri 02:17:26,597 INF Training Started                                                                                                
Fri 02:17:27,688 INF Epoch 21 - Batch 1 - Train Loss: 4.658428192138672                                                              
Fri 02:17:27,740 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:17:28,170 INF Epoch 21 - Batch 2 - Train Loss: 4.490416526794434                                                              
Fri 02:17:29,002 INF Epoch 21 - Batch 3 - Train Loss: 4.403616428375244                                                              
Fri 02:17:29,397 INF Epoch 21 - Batch 4 - Train Loss: 4.516929626464844                                                              
Fri 02:17:29,79

lr =  0.01


Fri 02:17:43,152 INF Epoch 21 - Batch 32 - Val Loss: 4.488                                                                           
Fri 02:17:43,267 INF Epoch 21 - Batch 32 - Val Loss: 9.158                                                                           
Fri 02:17:43,383 INF Epoch 21 - Batch 32 - Val Loss: 13.764                                                                          
Fri 02:17:43,498 INF Epoch 21 - Batch 32 - Val Loss: 18.340                                                                          
Fri 02:17:43,639 INF Epoch 21 - Batch 32 - Val Loss: 22.742                                                                          
Fri 02:17:43,750 INF Epoch 21 - Batch 32 - Val Loss: 27.309                                                                          
Fri 02:17:43,848 INF Epoch 21 - Batch 32 - Val Loss: 31.920                                                                          
Fri 02:17:43,952 INF Epoch 21 - Batch 32 - Val Loss: 36.316   

tensor([101,  57,  65,  14,  24,  24,  24,  95,  95,  24,  95,  24,  95,  24,
         24,  28,  58,  53,  95,  14,  95,  95,  24,  95,  28,  95,  95,  95])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:17:47,710 INF Epoch 21 - Best Model Saved                                                                                     
 70%|███████   | 21/30 [08:56<03:39, 24.43s/it]Fri 02:17:47,716 INF Training Started                                                                                                
Fri 02:17:48,863 INF Epoch 22 - Batch 1 - Train Loss: 4.588998317718506                                                              
Fri 02:17:48,902 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:17:49,300 INF Epoch 22 - Batch 2 - Train Loss: 4.4720258712768555                                                             
Fri 02:17:50,384 INF Epoch 22 - Batch 3 - Train Loss: 4.426878452301025                                                              
Fri 02:17:50,835 INF Epoch 22 - Batch 4 - Train Loss: 4.458521842956543                                                              
Fri 02:17:51,31

lr =  0.01


Fri 02:18:05,129 INF Epoch 22 - Batch 32 - Val Loss: 4.378                                                                           
Fri 02:18:05,254 INF Epoch 22 - Batch 32 - Val Loss: 9.126                                                                           
Fri 02:18:05,365 INF Epoch 22 - Batch 32 - Val Loss: 13.787                                                                          
Fri 02:18:05,478 INF Epoch 22 - Batch 32 - Val Loss: 18.367                                                                          
Fri 02:18:05,591 INF Epoch 22 - Batch 32 - Val Loss: 22.761                                                                          
Fri 02:18:05,696 INF Epoch 22 - Batch 32 - Val Loss: 27.492                                                                          
Fri 02:18:05,804 INF Epoch 22 - Batch 32 - Val Loss: 31.995                                                                          
Fri 02:18:05,913 INF Epoch 22 - Batch 32 - Val Loss: 36.565   

tensor([64, 64,  8, 95, 64, 27, 27, 27, 65, 65, 65, 95, 65, 27,  8, 53, 65,  8,
        64, 29, 95, 64, 27, 64, 74,  8, 95, 24])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:18:09,538 INF Epoch 22 - Best Model Saved                                                                                     
 73%|███████▎  | 22/30 [09:18<03:09, 23.65s/it]Fri 02:18:09,544 INF Training Started                                                                                                
Fri 02:18:10,728 INF Epoch 23 - Batch 1 - Train Loss: 4.734893798828125                                                              
Fri 02:18:10,775 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:18:11,174 INF Epoch 23 - Batch 2 - Train Loss: 4.387910842895508                                                              
Fri 02:18:11,942 INF Epoch 23 - Batch 3 - Train Loss: 4.470078468322754                                                              
Fri 02:18:12,341 INF Epoch 23 - Batch 4 - Train Loss: 4.521719932556152                                                              
Fri 02:18:12,77

lr =  0.01


Fri 02:18:26,554 INF Epoch 23 - Batch 32 - Val Loss: 4.430                                                                           
Fri 02:18:26,661 INF Epoch 23 - Batch 32 - Val Loss: 9.002                                                                           
Fri 02:18:26,771 INF Epoch 23 - Batch 32 - Val Loss: 13.675                                                                          
Fri 02:18:26,878 INF Epoch 23 - Batch 32 - Val Loss: 18.258                                                                          
Fri 02:18:26,995 INF Epoch 23 - Batch 32 - Val Loss: 22.808                                                                          
Fri 02:18:27,108 INF Epoch 23 - Batch 32 - Val Loss: 27.715                                                                          
Fri 02:18:27,216 INF Epoch 23 - Batch 32 - Val Loss: 32.221                                                                          
Fri 02:18:27,323 INF Epoch 23 - Batch 32 - Val Loss: 36.453   

tensor([58, 69, 53, 62, 62, 90, 90, 90, 53, 53, 58, 85, 24, 53, 90, 73, 24, 53,
        58, 29, 73, 58, 28, 69, 64, 24, 90, 90])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:18:31,199 INF Epoch 23 - Best Model Saved                                                                                     
 77%|███████▋  | 23/30 [09:39<02:41, 23.05s/it]Fri 02:18:31,206 INF Training Started                                                                                                
Fri 02:18:32,318 INF Epoch 24 - Batch 1 - Train Loss: 4.686354160308838                                                              
Fri 02:18:32,405 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:18:32,816 INF Epoch 24 - Batch 2 - Train Loss: 4.460823059082031                                                              
Fri 02:18:33,668 INF Epoch 24 - Batch 3 - Train Loss: 4.519868850708008                                                              
Fri 02:18:34,090 INF Epoch 24 - Batch 4 - Train Loss: 4.28275728225708                                                               
Fri 02:18:34,50

lr =  0.01


Fri 02:18:48,462 INF Epoch 24 - Batch 32 - Val Loss: 4.578                                                                           
Fri 02:18:48,573 INF Epoch 24 - Batch 32 - Val Loss: 9.030                                                                           
Fri 02:18:48,687 INF Epoch 24 - Batch 32 - Val Loss: 13.470                                                                          
Fri 02:18:48,797 INF Epoch 24 - Batch 32 - Val Loss: 18.007                                                                          
Fri 02:18:48,966 INF Epoch 24 - Batch 32 - Val Loss: 22.263                                                                          
Fri 02:18:49,067 INF Epoch 24 - Batch 32 - Val Loss: 26.709                                                                          
Fri 02:18:49,185 INF Epoch 24 - Batch 32 - Val Loss: 31.193                                                                          
Fri 02:18:49,295 INF Epoch 24 - Batch 32 - Val Loss: 35.350   

tensor([62, 64, 14, 62, 62, 62, 62, 62, 46, 62, 62,  4, 62, 94, 85, 64, 62, 62,
         4, 62, 62,  4, 62, 62, 62, 74, 62,  8])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:18:53,114 INF Epoch 24 - Best Model Saved                                                                                     
 80%|████████  | 24/30 [10:01<02:16, 22.71s/it]Fri 02:18:53,125 INF Training Started                                                                                                
Fri 02:18:54,298 INF Epoch 25 - Batch 1 - Train Loss: 4.697487831115723                                                              
Fri 02:18:54,349 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:18:54,783 INF Epoch 25 - Batch 2 - Train Loss: 4.337791919708252                                                              
Fri 02:18:55,528 INF Epoch 25 - Batch 3 - Train Loss: 4.251674652099609                                                              
Fri 02:18:55,957 INF Epoch 25 - Batch 4 - Train Loss: 4.437976360321045                                                              
Fri 02:18:56,39

lr =  0.01


Fri 02:19:10,307 INF Epoch 25 - Batch 32 - Val Loss: 4.386                                                                           
Fri 02:19:10,423 INF Epoch 25 - Batch 32 - Val Loss: 8.772                                                                           
Fri 02:19:10,537 INF Epoch 25 - Batch 32 - Val Loss: 13.246                                                                          
Fri 02:19:10,646 INF Epoch 25 - Batch 32 - Val Loss: 17.706                                                                          
Fri 02:19:10,799 INF Epoch 25 - Batch 32 - Val Loss: 21.815                                                                          
Fri 02:19:10,908 INF Epoch 25 - Batch 32 - Val Loss: 26.580                                                                          
Fri 02:19:11,036 INF Epoch 25 - Batch 32 - Val Loss: 31.084                                                                          
Fri 02:19:11,150 INF Epoch 25 - Batch 32 - Val Loss: 35.261   

tensor([53, 15,  7, 89, 15, 88, 88, 88, 97, 52, 90, 88, 33, 87, 87, 49, 80, 88,
        87, 24, 15, 49, 90, 83, 90, 28, 88, 29])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:19:15,164 INF Epoch 25 - Best Model Saved                                                                                     
 83%|████████▎ | 25/30 [10:23<01:52, 22.51s/it]Fri 02:19:15,170 INF Training Started                                                                                                
Fri 02:19:16,464 INF Epoch 26 - Batch 1 - Train Loss: 4.563019275665283                                                              
Fri 02:19:16,514 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:19:16,917 INF Epoch 26 - Batch 2 - Train Loss: 4.29458475112915                                                               
Fri 02:19:17,860 INF Epoch 26 - Batch 3 - Train Loss: 4.22118616104126                                                               
Fri 02:19:18,291 INF Epoch 26 - Batch 4 - Train Loss: 4.290815830230713                                                              
Fri 02:19:18,71

lr =  0.01


Fri 02:19:33,131 INF Epoch 26 - Batch 32 - Val Loss: 4.359                                                                           
Fri 02:19:33,242 INF Epoch 26 - Batch 32 - Val Loss: 8.519                                                                           
Fri 02:19:33,351 INF Epoch 26 - Batch 32 - Val Loss: 12.688                                                                          
Fri 02:19:33,459 INF Epoch 26 - Batch 32 - Val Loss: 17.062                                                                          
Fri 02:19:33,610 INF Epoch 26 - Batch 32 - Val Loss: 21.078                                                                          
Fri 02:19:33,725 INF Epoch 26 - Batch 32 - Val Loss: 25.533                                                                          
Fri 02:19:33,836 INF Epoch 26 - Batch 32 - Val Loss: 29.983                                                                          
Fri 02:19:33,947 INF Epoch 26 - Batch 32 - Val Loss: 34.314   

tensor([ 53,  57,  53,  45,  53,  39,  53,  25,  73,  57, 101, 100,  53,  90,
         89,   4,  89,  25,   4, 101,  73,  53,  73,  55,  53,   8,  90,  47])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:19:37,894 INF Epoch 26 - Best Model Saved                                                                                     
 87%|████████▋ | 26/30 [10:46<01:30, 22.58s/it]Fri 02:19:37,898 INF Training Started                                                                                                
Fri 02:19:38,924 INF Epoch 27 - Batch 1 - Train Loss: 4.580751895904541                                                              
Fri 02:19:38,971 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:19:39,450 INF Epoch 27 - Batch 2 - Train Loss: 4.2522125244140625                                                             
Fri 02:19:40,161 INF Epoch 27 - Batch 3 - Train Loss: 4.152569770812988                                                              
Fri 02:19:40,550 INF Epoch 27 - Batch 4 - Train Loss: 4.22581672668457                                                               
Fri 02:19:40,95

lr =  0.01


Fri 02:19:54,417 INF Epoch 27 - Batch 32 - Val Loss: 4.147                                                                           
Fri 02:19:54,521 INF Epoch 27 - Batch 32 - Val Loss: 8.326                                                                           
Fri 02:19:54,625 INF Epoch 27 - Batch 32 - Val Loss: 12.402                                                                          
Fri 02:19:54,728 INF Epoch 27 - Batch 32 - Val Loss: 16.599                                                                          
Fri 02:19:54,870 INF Epoch 27 - Batch 32 - Val Loss: 20.652                                                                          
Fri 02:19:54,988 INF Epoch 27 - Batch 32 - Val Loss: 25.173                                                                          
Fri 02:19:55,091 INF Epoch 27 - Batch 32 - Val Loss: 29.334                                                                          
Fri 02:19:55,195 INF Epoch 27 - Batch 32 - Val Loss: 33.543   

tensor([25, 57, 57, 25, 45, 25, 62, 25, 15, 25, 17, 57, 45,  8, 89, 15, 89, 25,
        38,  8, 57, 15, 15, 15, 15,  8, 25, 25])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:19:58,812 INF Epoch 27 - Best Model Saved                                                                                     
 90%|█████████ | 27/30 [11:07<01:06, 22.08s/it]Fri 02:19:58,819 INF Training Started                                                                                                
Fri 02:19:59,940 INF Epoch 28 - Batch 1 - Train Loss: 4.454444885253906                                                              
Fri 02:19:59,983 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:20:00,376 INF Epoch 28 - Batch 2 - Train Loss: 4.2185893058776855                                                             
Fri 02:20:01,110 INF Epoch 28 - Batch 3 - Train Loss: 4.161783218383789                                                              
Fri 02:20:01,501 INF Epoch 28 - Batch 4 - Train Loss: 4.139443874359131                                                              
Fri 02:20:01,91

lr =  0.01


Fri 02:20:15,415 INF Epoch 28 - Batch 32 - Val Loss: 4.006                                                                           
Fri 02:20:15,538 INF Epoch 28 - Batch 32 - Val Loss: 8.222                                                                           
Fri 02:20:15,658 INF Epoch 28 - Batch 32 - Val Loss: 12.659                                                                          
Fri 02:20:15,776 INF Epoch 28 - Batch 32 - Val Loss: 17.237                                                                          
Fri 02:20:15,915 INF Epoch 28 - Batch 32 - Val Loss: 20.970                                                                          
Fri 02:20:16,034 INF Epoch 28 - Batch 32 - Val Loss: 25.558                                                                          
Fri 02:20:16,153 INF Epoch 28 - Batch 32 - Val Loss: 29.825                                                                          
Fri 02:20:16,270 INF Epoch 28 - Batch 32 - Val Loss: 34.263   

tensor([70, 72, 15, 15, 58, 88, 70, 91, 34,  7,  1, 58, 58,  8, 39, 15, 72, 88,
        88, 70,  1, 15, 90,  1, 39, 70, 90, 88])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:20:20,095 INF Epoch 28 - Best Model Saved                                                                                     
 93%|█████████▎| 28/30 [11:28<00:43, 21.84s/it]Fri 02:20:20,106 INF Training Started                                                                                                
Fri 02:20:21,279 INF Epoch 29 - Batch 1 - Train Loss: 4.570610046386719                                                              
Fri 02:20:21,324 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:20:21,758 INF Epoch 29 - Batch 2 - Train Loss: 4.137739658355713                                                              
Fri 02:20:22,552 INF Epoch 29 - Batch 3 - Train Loss: 4.034238338470459                                                              
Fri 02:20:22,955 INF Epoch 29 - Batch 4 - Train Loss: 4.1671366691589355                                                             
Fri 02:20:23,36

lr =  0.01


Fri 02:20:36,984 INF Epoch 29 - Batch 32 - Val Loss: 3.996                                                                           
Fri 02:20:37,107 INF Epoch 29 - Batch 32 - Val Loss: 7.818                                                                           
Fri 02:20:37,230 INF Epoch 29 - Batch 32 - Val Loss: 12.084                                                                          
Fri 02:20:37,343 INF Epoch 29 - Batch 32 - Val Loss: 16.279                                                                          
Fri 02:20:37,568 INF Epoch 29 - Batch 32 - Val Loss: 20.298                                                                          
Fri 02:20:37,685 INF Epoch 29 - Batch 32 - Val Loss: 25.005                                                                          
Fri 02:20:37,793 INF Epoch 29 - Batch 32 - Val Loss: 29.094                                                                          
Fri 02:20:37,904 INF Epoch 29 - Batch 32 - Val Loss: 32.922   

tensor([67, 95, 53, 53, 53, 88, 88, 53,  3,  3, 88, 53, 88, 67, 27, 53, 89, 39,
        39, 72, 82, 53, 67, 53, 53, 24, 67, 88])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:20:41,800 INF Epoch 29 - Best Model Saved                                                                                     
 97%|█████████▋| 29/30 [11:50<00:21, 21.80s/it]Fri 02:20:41,804 INF Training Started                                                                                                
Fri 02:20:43,053 INF Epoch 30 - Batch 1 - Train Loss: 4.529094696044922                                                              
Fri 02:20:43,125 INF Gradcam not supported for model_data.fc                                                                         
Fri 02:20:43,525 INF Epoch 30 - Batch 2 - Train Loss: 4.207712173461914                                                              
Fri 02:20:44,354 INF Epoch 30 - Batch 3 - Train Loss: 3.9875621795654297                                                             
Fri 02:20:44,770 INF Epoch 30 - Batch 4 - Train Loss: 4.214232921600342                                                              
Fri 02:20:45,17

lr =  0.01


Fri 02:20:58,942 INF Epoch 30 - Batch 32 - Val Loss: 4.121                                                                           
Fri 02:20:59,068 INF Epoch 30 - Batch 32 - Val Loss: 8.102                                                                           
Fri 02:20:59,192 INF Epoch 30 - Batch 32 - Val Loss: 12.038                                                                          
Fri 02:20:59,311 INF Epoch 30 - Batch 32 - Val Loss: 16.330                                                                          
Fri 02:20:59,456 INF Epoch 30 - Batch 32 - Val Loss: 20.313                                                                          
Fri 02:20:59,570 INF Epoch 30 - Batch 32 - Val Loss: 24.451                                                                          
Fri 02:20:59,688 INF Epoch 30 - Batch 32 - Val Loss: 28.513                                                                          
Fri 02:20:59,804 INF Epoch 30 - Batch 32 - Val Loss: 32.485   

tensor([15, 70, 70, 70, 62, 17, 46, 39, 70, 38, 62, 82, 62, 25, 23, 62, 70, 23,
        46, 39, 17, 46, 46, 15, 46, 29, 17, 62])
tensor([ 99,  99,  99,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])


Fri 02:21:03,732 INF Epoch 30 - Best Model Saved                                                                                     
100%|██████████| 30/30 [12:12<00:00, 24.42s/it]


In [11]:
break here

SyntaxError: invalid syntax (<ipython-input-11-3ef470a3d0aa>, line 1)

In [ ]:
list(model_data.named_modules())

[('',
  MobileNetV3(
    (features): Sequential(
      (0): Conv2dNormActivation(
        (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): Hardswish()
      )
      (1): InvertedResidual(
        (block): Sequential(
          (0): Conv2dNormActivation(
            (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=16, bias=False)
            (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
            (2): ReLU(inplace=True)
          )
          (1): SqueezeExcitation(
            (avgpool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1))
            (fc2): Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1))
            (activation): ReLU()
            (scale_activation): Hardsigmoid()
          )
          (2): Conv2dNormActivation(


In [ ]:
print(model_data.avgpool)
print(model_data.classifier.in_features)

AdaptiveAvgPool2d(output_size=1)
576


In [ ]:
a =(model_data.avgpool)
print(a)
b = 'model_data.avgpool'
print(b)
print(b.split('.')[1])
c = eval(b)
print(c)


AdaptiveAvgPool2d(output_size=1)
model_data.avgpool
avgpool
AdaptiveAvgPool2d(output_size=1)
AdaptiveAvgPool2d(output_size=1)


In [ ]:
import tqdm
from pytorch_grad_cam import GradCAM
from mb_pytorch.utils.viewer import new_show_cam_on_image

model_data.to(device)

for i in tqdm.tqdm(range(20)):
        
        ##train loop
        
        model_data.train()
        train_loss = 0
        
        if logger:
            logger.info('Training Started')
        for j,(x,y) in enumerate(train_loader):
            x,y = x.to(device),y.to(device)
            optimizer.zero_grad()
            y_pred = model_data(x)
            current_loss = loss_attr()(y_pred,y)
            current_loss.backward()            
            optimizer.step()
            if scheduler is not None:
                scheduler.step()    
            train_loss += current_loss.item()
            if logger:
                logger.info(f'Epoch {i+1} - Batch {j+1} - Train Loss: {current_loss.item()}')
            
            #get grad cam images
            gradcam=['model_data.classifier']
            if gradcam and writer is not None:
                x_grad = x[0,:].to('cpu')
                x_grad = x_grad.unsqueeze(0)
                y_grad = y[0].to('cpu')
                for cam_layers in gradcam:
                    str_cam_layers = str(cam_layers)
                    print(str_cam_layers.split('.')[1])
                    grad_cam_layer= eval(cam_layers)
                    print(grad_cam_layer)
                    djkfals
                    
                    if logger:
                        logger.info(f'Gradcam for layer {cam_layers} started')
                    with GradCAM(model=model_data,target_layers=[cam_layers],use_cuda=False) as cm: 
                        try:
                            cr = cm(input_tensor=x_grad)[0,:]  
                        except:
                            cr = None 
                            if logger:
                                logger.info(f'Gradcam for layer {cam_layers} failed')
                        if cr is not None:
                            if logger:
                                logger.info(f'Gradcam for layer {cam_layers} completed')
                            cam_img = new_show_cam_on_image(x_grad[0].numpy(),cr,use_rgb=False)
                            writer.add_image(f'Gradcam/{cam_layers}',cam_img,global_step=i)
        avg_train_loss = train_loss / len(train_loader)
        if logger:
            logger.info(f'Epoch {i+1} - Train Loss: {avg_train_loss}')
    

  0%|          | 0/20 [00:00<?, ?it/s]Tue 13:37:04,193 INF Training Started                                                                                                
Tue 13:37:04,911 INF Epoch 1 - Batch 1 - Train Loss: 2.4315595626831055                                                              


classifier
Linear(in_features=576, out_features=10, bias=True)


  0%|          | 0/20 [00:00<?, ?it/s]


NameError: name 'djkfals' is not defined

In [ ]:
## old process

import tqdm
from torch.utils.tensorboard import SummaryWriter
import os


for i in tqdm.tqdm(range(all_model_data['model_epochs'])):
    ##train loop
    model_data.train()
    train_loss = 0
    for j,(x,y) in enumerate(train_loader10):
        x,y = x.to(device),y.to(device)
        optimizer.zero_grad()
        y_pred = model_data(x)
        current_loss = loss_attr()(y_pred,y)
        current_loss.backward()    
        optimizer.step()
        train_loss += current_loss.item()
        logger.info(f'Epoch {i+1} - Batch {j+1} - Train Loss: {current_loss.item()}')
    
    avg_train_loss = train_loss / len(train_loader)
    logger.info(f'Epoch {i+1} - Train Loss: {avg_train_loss}')
    
    writer.add_scalar('Loss/train', avg_train_loss, global_step=i)
        
    if scheduler is not None:
        scheduler.step()
    
    for name, param in model_data.named_parameters():
        writer.add_histogram(name, param, global_step=i)
        
    #get grad cam images
        
    #validation loop
    val_loss = 0
    val_acc = 0
    num_samples = 0
    
    model_data.eval()
    with torch.no_grad():
        for x_val, y_val in val_loader10:
            x_val, y_val = x_val.to(device), y_val.to(device)
            output = model_data(x_val)
            val_loss += loss_attr()(output, y_val).item() * x_val.size(0)
            _, preds = torch.max(output, 1)
            val_acc += torch.sum(preds == y_val.data)
            num_samples += x_val.size(0)
            logger.info(f'Epoch {i+1} - Batch {j+1} - Val Loss: {val_loss}')
        
        if num_samples == 0:
            num_samples = 1
        val_loss /= num_samples
        val_acc = val_acc / num_samples
        logger.info(f'Epoch {i+1} - Val Loss: {val_loss}', f'Epoch {i+1} - Val Acc: {val_acc}')
    
    writer.add_scalar('Loss/val', val_loss, global_step=i)
    writer.add_scalar('Accuracy/val', val_acc, global_step=i)
    
    # save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model = model_data.state_dict()

        path = os.path.join(all_data['data']['work_dir'], 'best_model.pth')
        torch.save(best_model, path)
        logger.info(f'Epoch {i+1} - Best Model Saved')
        
    model_data.train()
        


  0%|          | 0/50 [00:00<?, ?it/s]Tue 01:34:05,255 INF Epoch 1 - Batch 1 - Train Loss: 2.7716147899627686                                                              
Tue 01:34:07,058 INF Epoch 1 - Batch 2 - Train Loss: 3.0471785068511963                                                              
Tue 01:34:08,862 INF Epoch 1 - Batch 3 - Train Loss: 3.576723575592041                                                               
Tue 01:34:10,702 INF Epoch 1 - Batch 4 - Train Loss: 3.355401039123535                                                               
Tue 01:34:12,620 INF Epoch 1 - Batch 5 - Train Loss: 3.2821779251098633                                                              
Tue 01:34:14,500 INF Epoch 1 - Batch 6 - Train Loss: 3.361398220062256                                                               
Tue 01:34:16,429 INF Epoch 1 - Batch 7 - Train Loss: 3.22971510887146                                                                
Tue 01:34:18,368 INF Epo

In [ ]:
from mb_pytorch.utils.extra_utils import feature_view

for l in train_loader10:
    x,y = l
    break

from mb_pytorch.utils.extra_utils import get_model_summary
get_model_summary(model_data,input_size=(3,32,32))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 16, 16]           9,408
       BatchNorm2d-2           [-1, 64, 16, 16]             128
              ReLU-3           [-1, 64, 16, 16]               0
         MaxPool2d-4             [-1, 64, 8, 8]               0
            Conv2d-5             [-1, 64, 8, 8]           4,096
       BatchNorm2d-6             [-1, 64, 8, 8]             128
              ReLU-7             [-1, 64, 8, 8]               0
            Conv2d-8             [-1, 64, 8, 8]          36,864
       BatchNorm2d-9             [-1, 64, 8, 8]             128
             ReLU-10             [-1, 64, 8, 8]               0
           Conv2d-11            [-1, 256, 8, 8]          16,384
      BatchNorm2d-12            [-1, 256, 8, 8]             512
           Conv2d-13            [-1, 256, 8, 8]          16,384
      BatchNorm2d-14            [-1, 25

In [ ]:
list(model_data.named_modules()).index(('conv1', model_data.conv1))

1

In [ ]:
model_data.layer4[-1]

Bottleneck(
  (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
)

In [ ]:
list(model_data.named_modules()).index(('fc', model_data.fc))

150

In [ ]:
from mb_pytorch.models.modelloader import ModelLoader
from mb_pytorch.dataloader.loader import DataLoader
from mb_pytorch.training.train_params import train_helper
from torch.utils.tensorboard import SummaryWriter
import os
from mb_utils.src.logging import logger
import torch
from mb_pytorch.classification.training import classification_train_loop

k = DataLoader('/home/malav/jupyter_tests/Malav/classification.yaml')

k_data = k.data_dict['data']
model_data_dict = k.data_dict['model']

model_data_load = ModelLoader(k.data_dict['model'])
model_data =  model_data_load.get_model()
train_loader,val_loader,_,_ = k.data_load()
all_data = k.data_dict

model_yaml_data = k.data_dict['model']
loss_attr,optimizer_attr,optimizer_dict,scheduler_attr,scheduler_dict = train_helper(model_yaml_data)

optimizer =optimizer_attr(model_data.parameters(),**optimizer_dict)
scheduler = scheduler_attr(optimizer,**scheduler_dict)
best_val_loss = float('inf')
path_logs = os.path.join(all_data['data']['work_dir'], 'logs')
writer = SummaryWriter(log_dir=path_logs)
all_model_data= k.data_dict['model']

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

classification_train_loop(k_data,model_data_dict,model_data,train_loader,val_loader,loss_attr,optimizer,scheduler,writer,logger=logger,gradcam=['model_data.fc'],device=device)

